import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import { ApplicationGallery, CeralithBreakthrough, ComparisonGallery, DTPaperImpactAward, DTPaperRealContext, EvidencePanel, GovernanceAccordion, HeritageSection, IndustrialDataPanel, IndustrialJourney, IndustrialPhotoStory, MaterialOutcomes, PlatformCTA, PlatformFragmentation, PlatformHero, PlatformPeople, PlatformPhases, PlatformStoryCollage, PlatformSystem, ProductStoryGallery, ProjectForm, RecognitionSection } from "../../components";
import { ceralithComparisonRecords, evidenceRecords, galleryRecords, globalHubMediaRecords, industrialParameters, platformMediaRecords } from "../../../content/site";
import { trApplicationNotes, trInsights, trPages, trTechnologies } from "../../../content/tr";
import { corporateEmail } from "../../../content/contact";
import { leadershipProfiles } from "../../../content/leadership";

type Props={params:Promise<{slug:string[]}>};
const routes=Object.keys(trPages);
export async function generateStaticParams(){return [...routes.map(slug=>({slug:[slug]})),...trTechnologies.map(t=>({slug:["technologies",t.slug]})),...trInsights.map(a=>({slug:["insights",a.slug]}))]}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const key=slug.join("/");const tech=trTechnologies.find(t=>key===`technologies/${t.slug}`);const article=trInsights.find(a=>key===`insights/${a.slug}`);const page=trPages[key];const title=tech?.name||article?.title||page?.title||"PTP";const description=tech?.summary||article?.metaDescription||page?.intro||"PTP Plastikten Kâğıda Teknoloji Platformu";return {title,description,alternates:{canonical:`/tr/${key}`,languages:{"tr-TR":`/tr/${key}`,"en-GB":`/en/${key}`,"x-default":`/en/${key}`}},...(article?{openGraph:{type:"article",title,description,publishedTime:article.publishedIso,modifiedTime:article.updatedIso,authors:[article.author]},twitter:{card:"summary_large_image",title,description}}:{})}}

function Hero({eyebrow,title,intro}:{eyebrow:string;title:string;intro:string}){return <section className="page-hero"><p className="eyebrow light">{eyebrow}</p><h1>{title}</h1><p>{intro}</p><div className="page-hero-grid" aria-hidden="true"><i></i><i></i><i></i><i></i></div></section>}
function TrDisclaimer(){return <aside className="disclaimer"><b>Uygulama notu</b><p>Performans; altlığa, kaplama miktarına, proses koşullarına, dönüştürme konfigürasyonuna ve nihai kullanıma bağlıdır. Gıda teması, mevzuat, geri dönüştürülebilirlik ve uygulamaya özel iddialar hedef pazar ve kullanım için nihai yapıda doğrulanmalıdır.</p></aside>}
function CTA({title="Malzeme problemini bize getirin.",copy="PTP, endüstriyel bir yolun araştırılması için gerekli disiplinleri bir araya getirir.",accent}:{title?:string;copy?:string;accent?:string}){return <section className={`mini-cta contextual-cta ${accent||""}`}><h2>{title}</h2><p>{copy}</p><a className="button primary" href="/tr/contact">Proje Başlat <span aria-hidden="true">→</span></a></section>}

function TechPage({slug}:{slug:string}){
  const t=trTechnologies.find(x=>x.slug===slug);if(!t)notFound();
  const isD=t.slug==="dtpaper";const isC=t.slug==="ceralith";
  const steps=isD?["Baskı","Proses","Fiksaj","Transfer"]:isC?["Altlık","Mineral kaplama","Kurutma / reaksiyon","Dönüştürme ve validasyon"]:["Maruziyeti tanımla","Altlığı seç","Kaplamayı ayarla","Nihai kullanımı doğrula"];
  const collaborations=isD?["Baskı sistemi uyumluluk geliştirmesi","Tekstil uygulama validasyonu","Bölgesel tedarik veya lisanslama"]:isC?["Altlık ve kaplama ortak geliştirmesi","Fırın ve dönüştürme validasyonu","Üretim ve lisanslama ortaklığı"]:["Uygulamaya özel bariyer geliştirmesi","Kâğıt fabrikası ve dönüştürücü denemeleri","Tedarik, üretim veya lisanslama"];
  const heroMedia=isD?{src:"/story/dtpaper-step-textile-v2.webp",alt:"DTP tekstil transferi sonucunun temsili görünümü"}:isC?{src:"/story/ceralith-ovenable-tray-v3.webp",alt:"Markasız fırınlanabilir lif tepsi uygulama bağlamı"}:{src:"/story/bioma-pizza-box-application.webp",alt:"Temsili gıda ambalajı bağlamında oluklu lif bazlı servis kutusunda pizza"};
  return <>
    <section className={`page-hero product-hero product-${t.slug}`}><div className="product-hero-copy"><p className="eyebrow light">{t.label}</p><h1>{t.title}</h1><p>{t.summary}</p></div><div className="product-hero-media"><Image src={heroMedia.src} alt={heroMedia.alt} fill sizes="(max-width: 900px) calc(100vw - 44px), 55vw" quality={86} priority/><span>{t.name}</span><i></i><i></i><i></i></div></section>
    <section className="section tech-detail"><div><p className="eyebrow">Malzeme problemi</p><h2>{isD?"DTF prosesinin tamamına göre geliştirildi.":isC?"Isı, yağ ve dönüştürme birlikte yönetilmelidir.":"Performans uygulamaya ve altlığa göre ayarlanır."}</h2><p className="lead-dark">{isD?"DTPaper® yalnızca PET filme alternatif bir tabaka değil; baskı, tozlama, fiksaj, transfer ve kontrollü ayrılma aşamalarını birlikte ele alan bir transfer sistemidir.":isC?"Ceralith™, PET film kullanmadan fırınlanabilir lif yapıları geliştirmeyi hedefleyen su bazlı mineral-reaktif kaplama teknolojisidir.":"Bioma-ORX®, farklı yağ, gres, nem ve dönüştürme gereksinimlerine göre ayarlanabilen su bazlı, PFAS içermeyen bariyer platformudur."}</p></div><div className={`material-sample ${isD?"fibre":isC?"mineral":"barrier"}`}><span>{t.name}</span><i></i><i></i><i></i></div></section>
    <section className="section tech-process"><p className="eyebrow">Uygulama prosesi</p><h2>İş akışının bütünü için tasarlandı.</h2><div className="four-flow">{steps.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div></section>
    {isD&&<><ProductStoryGallery technology={t.slug} locale="tr"/><DTPaperRealContext locale="tr"/><DTPaperImpactAward locale="tr"/></>}<ApplicationGallery items={galleryRecords[t.slug]} locale="tr" eyebrow={isD?"Uygulamada DTPaper®":isC?"Ceralith™ Uygulama Keşfi":"Bioma-ORX® Kaydedilmiş Yağ Bariyeri Gösterimi"} heading={isD?"Baskı, proses, fiksaj ve transfer—tek kontrollü akışta belgelenir.":isC?"Gerçek bir kullanım gösterimi; performans kanıtı değil, uygulama bağlamı olarak yayımlanır.":"Kaydedilmiş OCC yağ bariyeri görüntüsü, temsili uygulama görsellerinden ayrı tutulur."}/>{!isD&&<ProductStoryGallery technology={t.slug} locale="tr"/>} {isC&&<CeralithBreakthrough locale="tr"/>}
    <section className="section capability-grid-section"><div><p className="eyebrow">Teknik kabiliyetler</p><h2>Birbirine bağlı gereksinimler.</h2></div><div className="capability-grid">{t.capabilities.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3></article>)}</div></section>
    <section className="section applications"><div><p className="eyebrow">Uygulamalar</p><h2>Odaklı endüstriyel kullanım için.</h2></div><div className="application-list">{t.applications.map(x=><span key={x}>{x}</span>)}</div></section>
    <EvidencePanel records={evidenceRecords[t.slug]} locale="tr"/>{isC&&<ComparisonGallery items={ceralithComparisonRecords} locale="tr"/>}<aside className="disclaimer"><b>Uygulama notu</b><p>{trApplicationNotes[t.slug]}</p></aside>
    <section className="section business-model"><p className="eyebrow">İş birliği yolları</p><h2>Teknolojiden pazara birden fazla yol.</h2><div className="model-list">{collaborations.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></section><CTA title={isD?"Kâğıt bazlı bir DTF iş akışını keşfedin.":isC?"Fırınlanabilir bir lif yapısı geliştirin.":"Uygulamanızın ihtiyaç duyduğu bariyer profilini tanımlayın."} accent={`cta-${t.slug}`}/>
  </>
}

function Insights(){return <><Hero {...trPages.insights}/><section className="section insight-grid">{trInsights.map(a=><article key={a.slug}><span>{a.category} · {a.readingTime}</span><h2>{a.title}</h2><p>{a.intro}</p><a className="arrow-link" href={`/tr/insights/${a.slug}`}>Makaleyi oku ↗</a></article>)}</section></>}
function Article({slug}:{slug:string}){const a=trInsights.find(x=>x.slug===slug);if(!a)notFound();const siteUrl=(process.env.NEXT_PUBLIC_SITE_URL||"https://ptp.technology").replace(/\/$/,"");const structuredData={"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.metaDescription,datePublished:a.publishedIso,dateModified:a.updatedIso,author:{"@type":"Organization",name:a.author},publisher:{"@type":"Organization",name:"Plastic-to-Paper Technology Platform"},inLanguage:"tr-TR",mainEntityOfPage:`${siteUrl}/tr/insights/${a.slug}`};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><Hero eyebrow={a.category} title={a.title} intro={a.intro}/><article className="article-body"><dl className="article-meta"><div><dt>Yayın</dt><dd><time dateTime={a.publishedIso}>{a.published}</time></dd></div><div><dt>Güncelleme</dt><dd><time dateTime={a.updatedIso}>{a.updated}</time></dd></div><div><dt>Yazar</dt><dd>{a.author}</dd></div><div><dt>Okuma süresi</dt><dd>{a.readingTime}</dd></div></dl>{a.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<div className="article-cta"><p className="eyebrow">İlgili teknoloji</p><h2>{a.technology}</h2><div className="actions"><a className="button primary" href={a.href}>Teknolojiyi incele</a><a className="button dark-outline" href="/tr/contact">Proje Başlat</a></div></div><TrDisclaimer/></article></>}

function LeadershipTr(){const profiles=leadershipProfiles.filter(p=>p.publicationApproved);if(!profiles.length)return null;return <section className="section leadership"><div className="section-head"><p className="eyebrow">Liderlik ve Teknik Yön</p><h2>Platform yönü ve teknik geliştirmeden sorumlu ekip.</h2></div><div className="leadership-grid">{profiles.map(p=><article key={p.fullName}><Image src={p.photograph} alt={p.photographAlt} width={640} height={760}/><span>{p.organisation}</span><h3>{p.fullName}</h3><b>{p.role}</b><p>{p.shortBiography}</p><p>{p.technicalExpertise.join(" · ")}</p><p>{p.relevantExperience}</p>{p.approvedProfileUrl&&<a className="partner-cta" href={p.approvedProfileUrl} rel="noreferrer">Profesyonel profil ↗</a>}</article>)}</div></section>}

function IndustrialTr(){return <><Hero {...trPages["industrial-scale"]}/><IndustrialPhotoStory locale="tr"/><IndustrialJourney locale="tr"/><ApplicationGallery items={galleryRecords["industrial-scale"]} locale="tr" eyebrow="Uygulamada endüstriyel ölçek" heading="Onaylı makine, kaplama ve kalite kontrol kanıtı."/><IndustrialDataPanel records={industrialParameters} locale="tr"/><CTA title="Bir kaplama teknolojisini endüstriyel üretime taşıyın." accent="cta-industrial"/></>}

function Contact(){const addresses=[["Genel talepler",corporateEmail.generalEnquiries],["Teknoloji projeleri",corporateEmail.technologyProjects],["Lisanslama ve iş birlikleri",corporateEmail.licensingAndPartnerships]].filter((x):x is [string,string]=>Boolean(x[1]));const grouped=[...new Set(addresses.map(([,address])=>address))].map(address=>({address,label:addresses.filter(([,value])=>value===address).map(([label])=>label).join(" · ")}));return <><Hero {...trPages.contact}/><section className="section contact-layout"><div><p className="eyebrow">Doğru başlangıç noktası</p><h2>Mevcut yapıyı veya yalnızca problemi getirin.</h2><p>PTP markalar, kâğıt fabrikaları, dönüştürücüler, baskıcılar, kimya geliştiricileri, OEM’ler, araştırmacılar ve stratejik ortaklarla çalışır.</p><div className="contact-facts"><div><span>Hedef ilk yanıt</span><b>İki iş günü içinde</b></div><div><span>Teknik geliştirme ve endüstriyelleştirme</span><b>Türkiye</b></div><div><span>Bilim, lisanslama ve uluslararasılaşma ağı</span><b>Cambridge ekosistemi</b></div>{grouped.map(item=><div key={item.address}><span>{item.label}</span><a href={`mailto:${item.address}`}>{item.address}</a></div>)}</div></div><ProjectForm locale="tr"/></section><section className="section next-steps"><div className="section-head"><p className="eyebrow">Sonrasında ne olur?</p><h2>Başvurudan projeye açık bir yol.</h2></div><div className="four-flow">{[["İlk değerlendirme","Uygulama ve mevcut bilgiler incelenir."],["Teknik görüşme","Malzeme, proses ve ticari sorular netleştirilir."],["Uygulama ve validasyon planı","Kapsam, yapı, test bağlamı ve karar ölçütleri tanımlanır."],["Ticari veya ortaklık yolu","Tedarik, lisanslama, bölgesel üretim veya ortak geliştirme değerlendirilir."]].map(([a,b],i)=><div key={a}><span>0{i+1}</span><b>{a}</b><p>{b}</p></div>)}</div></section></>}

function Generic({pageKey}:{pageKey:string}){const p=trPages[pageKey];if(!p)notFound();if(pageKey==="platform")return <><PlatformHero locale="tr"/><PlatformFragmentation locale="tr"/><PlatformSystem locale="tr"/><PlatformStoryCollage locale="tr"/><PlatformPeople locale="tr"/><GovernanceAccordion locale="tr"/><LeadershipTr/><PlatformPhases locale="tr"/><ApplicationGallery items={platformMediaRecords} locale="tr" eyebrow="Platform faaliyeti" heading="İnsanlar, gösterimler ve iş birlikleri bağlamıyla."/><MaterialOutcomes locale="tr"/><PlatformCTA locale="tr"/></>;return <><Hero {...p}/>{pageKey==="technologies"?<section className="section technologies"><div className="tech-grid">{trTechnologies.map((t,i)=><article className="tech-card" key={t.slug}><div className="tech-index">0{i+1}</div><p className="eyebrow">{t.label}</p><h3>{t.name}</h3><h4>{t.title}</h4><p>{t.summary}</p><a className="arrow-link" href={`/tr/technologies/${t.slug}`}>İncele ↗</a></article>)}</div></section>:<section className="section module-grid">{p.sections.map(([h,c],i)=><article key={h}><span>0{i+1}</span><h2>{h}</h2><p>{c}</p>{pageKey==="partners"&&<a className="partner-cta" href="/tr/contact">İş birliği yolunu görüşün ↗</a>}</article>)}</section>}{pageKey==="partners"&&<RecognitionSection locale="tr"/>}{pageKey==="about"&&<HeritageSection locale="tr"/>}{pageKey==="global-hub"&&<ApplicationGallery items={globalHubMediaRecords} locale="tr" eyebrow="Merkez faaliyeti" heading="Onaylı ekip, ortaklık ve etkinlik medyası."/>}<CTA/></>}

export default async function TrDynamic({params}:Props){const {slug}=await params;const key=slug.join("/");if(slug[0]==="technologies"&&slug[1])return <TechPage slug={slug[1]}/>;if(key==="industrial-scale")return <IndustrialTr/>;if(key==="insights")return <Insights/>;if(slug[0]==="insights"&&slug[1])return <Article slug={slug[1]}/>;if(key==="contact")return <Contact/>;return <Generic pageKey={key}/>}
