import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import test from "node:test";

async function fetchRoute(path = "/en") {
  const workerUrl = new URL(`../dist/server/index.js?test=${process.pid}-${Date.now()}-${encodeURIComponent(path)}`, import.meta.url);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${path}`, { headers: { accept: "text/html" } }), { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } }, { waitUntil() {}, passThroughOnException() {} });
}

test("homepage communicates the platform proposition", async () => { const response=await fetchRoute();assert.equal(response.status,200);const html=await response.text();assert.match(html,/From Plastic Dependence/i);assert.match(html,/Three technologies\. Three plastic-to-paper pathways/i);assert.doesNotMatch(html,/codex-preview|react-loading-skeleton/i); });
test("primary routes render", async () => { for (const route of ["/en/platform","/en/technologies","/en/how-we-work","/en/industrial-scale","/en/global-hub","/en/insights","/en/contact"]) { const response=await fetchRoute(route);assert.equal(response.status,200,route); } });
test("technology pages use exact non-repeating hero copy", async () => { const cases=[["dtpaper","A paper-based, PET-film-free and silicone-free transfer system engineered for the complete Direct-to-Film textile printing workflow.",/transfer medium designed for Direct-to-Film/],["ceralith","A water-based mineral-reactive coating technology designed to enable ovenable paper and board structures without PET film.",/designed without PET film\. A water-based/],["bioma-orx","An adjustable, water-based and PFAS-free barrier platform designed for oil, grease, moisture and selected liquid resistance on paper and board.",/barrier platform for paper and board\. A water-based/]];for(const [slug,copy,duplicate] of cases){const response=await fetchRoute(`/en/technologies/${slug}`);const html=await response.text();const visible=html.slice(html.indexOf("<main>"),html.indexOf("</main>"));assert.match(visible,new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")),slug);assert.doesNotMatch(visible,duplicate,slug);} });
test("technology pages expose professional evidence and product-specific notes", async () => { const notes={dtpaper:/selected printer, ink, hot-melt powder/i,ceralith:/selected paper or board, coating weight/i,"bioma-orx":/substrate, coating weight, oil and moisture exposure/i};for(const slug of ["dtpaper","ceralith","bioma-orx"]){const response=await fetchRoute(`/en/technologies/${slug}`);const html=await response.text();assert.match(html,/Validation &amp; application evidence/i);assert.match(html,/Selected application evidence is published after technical, source and confidentiality review/i);assert.match(html,notes[slug]);assert.doesNotMatch(html,/Awaiting assets|coming soon|placeholder|Recognition records are published/i);} });
test("Turkish routes and language selector render", async () => { for(const route of ["/tr","/tr/platform","/tr/technologies/dtpaper","/tr/insights/ovenable-paperboard-plastic-film","/tr/contact"]){const response=await fetchRoute(route);assert.equal(response.status,200,route);const html=await response.text();assert.match(html,/href="\/tr|lang="tr"/i);} });
test("Turkish technology copy and evidence fallback are localised", async () => {const response=await fetchRoute("/tr/technologies/dtpaper");const html=await response.text();assert.match(html,/Direct-to-Film tekstil baskı sürecinin tamamına göre geliştirilmiş/);assert.match(html,/Seçilmiş uygulama kanıtları teknik inceleme/);assert.match(html,/kullanılan yazıcı, mürekkep, sıcak eriyik toz/);});
test("unapproved public contact and leadership placeholders remain hidden", async () => {for(const route of ["/en/contact","/en/about","/tr/contact","/tr/platform"]){const html=await (await fetchRoute(route)).text();assert.doesNotMatch(html,/Provided through the secure project channel|Public biographies will be added|Platform direction|Technical authority should be visible/i);}});
test("industrial evidence falls back without representative gallery cards", async () => {for(const locale of ["en","tr"]){const html=await (await fetchRoute(`/${locale}/industrial-scale`)).text();assert.doesNotMatch(html,/Technical gallery|Industrial coating line|Pilot application/);assert.match(html,locale==="en"?/Detailed operating parameters are disclosed/:/Ayrıntılı çalışma parametreleri/);}});
test("insight articles include full structure and editorial metadata", async () => {for(const route of ["/en/insights/hidden-plastic-carrier-dtf","/tr/insights/hidden-plastic-carrier-dtf"]){const html=await (await fetchRoute(route)).text();assert.match(html,route.startsWith("/en")?/Executive summary/:/Yönetici özeti/);assert.match(html,route.startsWith("/en")?/Industrial integration requirements/:/Endüstriyel entegrasyon gereksinimleri/);assert.match(html,/2026/);assert.match(html,route.startsWith("/en")?/Start a Project/:/Proje Başlat/);}});
test("all published pages and internal CTA destinations resolve", async () => {const base=["","platform","technologies","technologies/dtpaper","technologies/ceralith","technologies/bioma-orx","how-we-work","industrial-scale","for-brands","partners","global-hub","innovation-pipeline","insights","insights/industrial-integration-problem","insights/hidden-plastic-carrier-dtf","insights/pfas-free-industrial-packaging","insights/ovenable-paperboard-plastic-film","about","contact","privacy","cookies","technical-disclaimer"];const routes=[...new Set(["/en","/tr",...base.flatMap(path=>[...(["en","tr"].map(locale=>`/${locale}${path?`/${path}`:""}`))])])];const discovered=new Set();for(const route of routes){const response=await fetchRoute(route);assert.equal(response.status,200,route);const html=await response.text();for(const match of html.matchAll(/href="(\/[^"]*)"/g)){const href=match[1].split(/[?#]/)[0];if(href.startsWith("/en")||href.startsWith("/tr"))discovered.add(href);}}for(const href of discovered){const response=await fetchRoute(href);assert.equal(response.status,200,href);}});
test("contact endpoint validates fields, email and consent", async () => { const workerUrl=new URL(`../dist/server/index.js?api=${Date.now()}`,import.meta.url);const {default:worker}=await import(workerUrl.href);const env={ASSETS:{fetch:async()=>new Response("Not found",{status:404})}};const ctx={waitUntil(){},passThroughOnException(){}};const post=body=>worker.fetch(new Request("http://localhost/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),env,ctx);assert.equal((await post({})).status,400);const base={name:"A",company:"B",country:"TR",description:"Project"};assert.equal((await post({...base,email:"not-an-email",consent:"accepted"})).status,400);assert.equal((await post({...base,email:"a@b.com"})).status,400);assert.equal((await post({...base,email:"a@b.com",consent:"accepted"})).status,503); });
test("articles expose calculated reading time, semantic dates and Article JSON-LD", async () => {for(const [route,reading] of [["/en/insights/hidden-plastic-carrier-dtf",/4 min read/],["/tr/insights/hidden-plastic-carrier-dtf",/4 dk okuma/]]){const html=await(await fetchRoute(route)).text();assert.match(html,reading);assert.match(html,/<time datetime="2026-08-13">/i);assert.match(html,/application\/ld\+json/);assert.match(html,/&quot;@type&quot;:&quot;Article&quot;|"@type":"Article"/);assert.match(html,/datePublished/);assert.match(html,/dateModified/);}});
test("approved technology media remains on product pages and homepage links to it", async () => {
  const home=await(await fetchRoute("/en")).text();
  assert.doesNotMatch(home,/Technology in Motion|Watch Demonstration|Evidence context|<video/);
  for(const slug of ["dtpaper","ceralith","bioma-orx"]) assert.match(home,new RegExp(`/en/technologies/${slug}#recorded-demonstration`));
  for(const technology of ["DTPaper®","Ceralith™","Bioma-ORX®"]) assert.match(home,new RegExp(technology.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
  const expected={dtpaper:["/media/dtpaper-workflow.webm","/media/dtpaper-workflow.mp4","/media/dtpaper-workflow-en.vtt"],ceralith:["/media/ceralith-ovenable-demo.webm","/media/ceralith-ovenable-demo.mp4","/media/ceralith-ovenable-demo-en.vtt"],"bioma-orx":["/media/bioma-oil-barrier-occ.webm","/media/bioma-oil-barrier-occ.mp4","/media/bioma-oil-barrier-occ-en.vtt"]};
  for(const slug of Object.keys(expected)){
    const html=await(await fetchRoute(`/en/technologies/${slug}`)).text();
    assert.match(html,/id="recorded-demonstration"/);
    assert.match(html,/<video[^>]*playsinline=""[^>]*preload="metadata"/i);
    assert.match(html,/class="media-player media-player-/);
    assert.match(html,/Watch demonstration/);
    assert.match(html,/Evidence context/);
    assert.match(html,/<picture>/);
    for(const path of expected[slug]) assert.match(html,new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
    assert.match(html,/<track[^>]*kind="captions"/i);
    assert.match(html,/Download or open the demonstration video/);
    assert.doesNotMatch(html,/Location not supplied|Date not supplied|Not supplied|Publication status|Confidentiality and publication review approved/i);
    assert.doesNotMatch(html,/canapa arge|Canapa_DTF|bıoma 2|bioma 3|ceralıth 2/i);
  }
  const trHtml=await(await fetchRoute("/tr/technologies/dtpaper")).text();
  assert.match(trHtml,/id="recorded-demonstration"/);
  assert.match(trHtml,/sağlanan proses görüntüleri/);
  assert.match(trHtml,/dtpaper-workflow-tr\.webm/);
  assert.match(trHtml,/dtpaper-workflow-tr\.vtt/);
  assert.doesNotMatch(trHtml,/Location not supplied|Konum bilgisi sağlanmadı|Sağlanmadı|Publication status|Yayın statüsü/i);
  const source=await readFile(new URL("../content/site.ts",import.meta.url),"utf8");
  for(const field of ["copyrightApproved","confidentialityApproved","personConsentApproved","technicalReviewApproved","publicationApproved","approvedBy","approvalDate"]) assert.match(source,new RegExp(field));
  for(const file of ["dtpaper-workflow.mp4","dtpaper-workflow.webm","dtpaper-workflow-tr.webm","ceralith-ovenable-demo-mobile.mp4","bioma-oil-barrier-occ.webm","bioma-oil-barrier-occ-en.vtt"]) assert.ok((await stat(new URL(`../public/media/${file}`,import.meta.url))).size>0,file);
  for(const stem of ["dtpaper-workflow","ceralith-ovenable-demo","bioma-oil-barrier-occ"]) for(const suffix of ["poster-v2.webp","poster-mobile-v2.webp","poster-thumbnail-v2.webp","poster-modal-v2.webp"]) assert.ok((await stat(new URL(`../assets/posters/${stem}-${suffix}`,import.meta.url))).size>4_000,`${stem}-${suffix}`);
});
test("visual energy redesign keeps content distinct, accessible, and approval-safe",async()=>{const home=await(await fetchRoute("/en")).text();assert.match(home,/CHEMISTRY/);for(const marker of ["home-tech-grid","lab-scale-strip","home-integration","home-global-grid","home-recognition","home-final-cta"])assert.match(home,new RegExp(marker));assert.match(home,/Three technologies\. Three plastic-to-paper pathways/);assert.doesNotMatch(home,/TechnologyCards|portfolio-compare/);const platform=await(await fetchRoute("/en/platform")).text();for(const marker of ["platform-hero","fragment-map","system-map","platform-story","platform-people","governance-accordion","phase-grid","outcomes-track","platform-final-cta"])assert.match(platform,new RegExp(marker));assert.match(platform,/aria-expanded="true"/);assert.match(platform,/aria-controls="governance-en-panel-0"/);const industrial=await(await fetchRoute("/en/industrial-scale")).text();for(const stage of ["Develop","Integrate","Scale"])assert.match(industrial,new RegExp(`>${stage}<`));assert.doesNotMatch(industrial,/canapa arge/i);for(const slug of ["dtpaper","ceralith","bioma-orx"]){const html=await(await fetchRoute(`/en/technologies/${slug}`)).text();assert.match(html,new RegExp(`product-${slug}`));assert.match(html,/Technical record/);assert.match(html,/visitor-metadata/);}const content=await readFile(new URL("../content/site.ts",import.meta.url),"utf8");for(const text of ["Process footage supplied by Canapa Paper Technologies","Application footage supplied by Canapa Paper Technologies","Demonstration footage supplied by Canapa Paper Technologies"])assert.match(content,new RegExp(text));const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");for(const colour of ["#8FE36A","#B6E84B","#D7B65B","#C96D4B","#5CC8C2"])assert.match(css,new RegExp(colour,"i"));assert.match(css,/prefers-reduced-motion:reduce/);assert.ok((await stat(new URL("../public/og-home-v2.png",import.meta.url))).size>1_000_000);});
test("responsive poster routes return real WebP responses", async () => {for(const stem of ["dtpaper-workflow","ceralith-ovenable-demo","bioma-oil-barrier-occ"]) for(const suffix of ["poster-v2.webp","poster-mobile-v2.webp","poster-thumbnail-v2.webp","poster-modal-v2.webp"]){const poster=`${stem}-${suffix}`;const response=await fetchRoute(`/media/${poster}`);assert.equal(response.status,200,poster);assert.equal(response.headers.get("content-type"),"image/webp",poster);assert.ok((await response.arrayBuffer()).byteLength>4_000,poster);}});
test("technology pages keep the requested product-story order", async () => {for(const slug of ["dtpaper","ceralith","bioma-orx"]){const html=await(await fetchRoute(`/en/technologies/${slug}`)).text();const labels=["The material challenge","Application process",slug==="dtpaper"?"DTPaper® Application in Practice":slug==="ceralith"?"Ceralith™ Application Exploration":"Bioma-ORX® Oil Barrier Demonstration","Technical capabilities","Applications","Validation &amp; application evidence","Application note","Collaboration pathways"];let previous=-1;for(const label of labels){const current=html.indexOf(label);assert.ok(current>previous,`${slug}: ${label}`);previous=current;}}});
test("resolution-restored story media is responsive and source-honest", async () => {const dtpaper=await(await fetchRoute("/en/technologies/dtpaper")).text();assert.match(dtpaper,/dtpaper-process-timeline/);assert.match(dtpaper,/Watch full recorded workflow/);assert.match(dtpaper,/representative process visualisations created to explain the DTPaper/);assert.match(dtpaper,/not published as standalone performance or equipment evidence/);for(const stage of ["print","powder","cure","transfer"]){assert.match(dtpaper,new RegExp(`dtpaper-process-${stage}-v3\\.webp`));assert.match(dtpaper,new RegExp(`dtpaper-process-${stage}-mobile-v3\\.webp`));}const ceralith=await(await fetchRoute("/en/technologies/ceralith")).text();for(const file of ["ceralith-ovenable-tray-v3.webp","ceralith-frozen-food-packaging-v1.webp","ceralith-paper-cup-coating-v1.webp","ceralith-bakery-application-v1.webp"])assert.match(ceralith,new RegExp(file.replaceAll(".","\\.")));const bioma=await(await fetchRoute("/en/technologies/bioma-orx")).text();for(const file of ["bioma-fast-food-wrap-v3.webp","bioma-fried-food-v3.webp","bioma-bakery-bag-v3.webp","bioma-snack-pack-v3.webp","bioma-butter-wrap-v3.webp","bioma-fibre-takeaway-v3.webp"])assert.match(bioma,new RegExp(file.replaceAll(".","\\.")));for(const file of ["dtpaper-process-print-v3.webp","dtpaper-process-print-mobile-v3.webp","dtpaper-process-powder-v3.webp","dtpaper-process-powder-mobile-v3.webp","dtpaper-process-cure-v3.webp","dtpaper-process-cure-mobile-v3.webp","dtpaper-process-transfer-v3.webp","dtpaper-process-transfer-mobile-v3.webp","ceralith-paper-cup-coating-v1.webp","bioma-fast-food-wrap-v3.webp"])assert.ok((await stat(new URL(`../public/story/${file}`,import.meta.url))).size>4_000,file);});
test("green-transition palette and robust form states are present", async () => {const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");for(const colour of ["#092E27","#0E4D3D","#34745E","#75C88A","#F1F2E9","#F7F4EA","#D9E4D6","#202522"])assert.match(css,new RegExp(colour,"i"));assert.match(css,/prefers-reduced-motion:reduce/);const form=await readFile(new URL("../app/components.tsx",import.meta.url),"utf8");for(const state of ["sending","sent","error","timeout","duplicate"])assert.match(form,new RegExp(`\\"${state}\\"`));assert.match(form,/Your details remain in the form/);assert.match(form,/Bilgileriniz formda korundu/);assert.match(form,/aria-invalid/);assert.match(form,/aria-describedby/);assert.match(form,/method="post" action="\/api\/contact"/);});
test("photographic narrative separates representative promotion, recorded evidence, and recognition", async () => {const home=await(await fetchRoute("/en")).text();assert.match(home,/home-hero-visual/);assert.equal((home.match(/AI-generated representative image/g)||[]).length,1);assert.match(home,/home-hero-plastic-crisis-v4\.webp/);assert.doesNotMatch(home,/Recorded process documentation|Application exploration footage|Comparative application demonstration/);assert.match(home,/Verified primary record/);const industrial=await(await fetchRoute("/en/industrial-scale")).text();assert.match(industrial,/From formulation and material testing to coating, validation and industrial scale-up/);assert.match(industrial,/Canapa Innovation Center .*R&amp;D and application development environment/);const dtpaper=await(await fetchRoute("/en/technologies/dtpaper")).text();for(const stage of ["Print","Powder","Curing","Transfer","Final textile"])assert.match(dtpaper,new RegExp(`>${stage}<`));assert.match(dtpaper,/Representative outcome visualisation/);const ceralith=await(await fetchRoute("/en/technologies/ceralith")).text();for(const category of ["Ovenable fibre trays","Bakery applications","Frozen food packaging","Cupboard coatings"])assert.match(ceralith,new RegExp(category));const bioma=await(await fetchRoute("/en/technologies/bioma-orx")).text();for(const category of ["Fast-food wrapping","Fried food packaging","Bakery bags","Popcorn and snacks","Butter and fatty-food wrapping","Fibre takeaway containers"])assert.match(bioma,new RegExp(category));assert.match(bioma,/Recorded OCC oil-barrier footage/);assert.match(bioma,/Target application category/);const partners=await(await fetchRoute("/en/partners")).text();for(const fact of ["WTiN Innovate Textile Awards","Winner of Sustainability","5 December 2025","This recognition belongs to Canapa"])assert.match(partners,new RegExp(fact));for(const html of [home,industrial,dtpaper,ceralith,bioma,partners])assert.doesNotMatch(html,/DisneyFoodBlog|Parker(?:â€™|'|&apos;)s Kitchen|Labneli IspanaklÄ±/i);for(const file of ["canapa-innovation-center.webp","dtpaper-step-print-v2.webp","dtpaper-step-textile-v2.webp","ceralith-ovenable-tray-v3.webp","bioma-fast-food-wrap-v3.webp","bioma-butter-wrap-v3.webp","canapa-award-certificate-2025.webp"])assert.ok((await stat(new URL(`../public/story/${file}`,import.meta.url))).size>4_000,file);});
test("DTPaper real development context uses the six supplied photographs in one compact grid", async () => {const html=await(await fetchRoute("/en/technologies/dtpaper")).text();assert.match(html,/dtpaper-context-grid/);for(const file of ["dtpaper-context-roll-process.webp","dtpaper-context-liquid-test.webp","dtpaper-context-data-analysis.webp","dtpaper-context-thermal-test.webp","dtpaper-context-paper-production.webp","dtpaper-context-laboratory-work.webp"]){assert.match(html,new RegExp(file.replaceAll(".","\\.")));assert.ok((await stat(new URL(`../public/story/${file}`,import.meta.url))).size>4_000,file);}});

test("Bioma application field starts with the pizza box and excludes recorded observation cards", async () => {for(const locale of ["en","tr"]){const html=await(await fetchRoute(`/${locale}/technologies/bioma-orx`)).text();assert.match(html,locale==="en"?/Seven target packaging formats/:/Yedi hedef ambalaj formatı/);const gallery=html.indexOf(locale==="en"?"Seven target packaging formats":"Yedi hedef ambalaj formatı");const pizza=html.indexOf("bioma-pizza-box-application.webp",gallery);const wrap=html.indexOf("bioma-fast-food-wrap-v3.webp",gallery);assert.ok(gallery>=0&&pizza>gallery&&wrap>pizza);for(const removed of ["Untreated OCC","Treated structure","Oil application","Comparative observation","İşlem görmemiş OCC","İşlem görmüş yapı","Yağ uygulaması","Karşılaştırmalı gözlem","Four recorded observations"])assert.doesNotMatch(html,new RegExp(removed));}});
