import { calculateReadingTime } from "./site";

export const trProcess=["Malzeme problemi","Kimya ve malzeme tasarımı","Kâğıt / altlık mühendisliği","Endüstriyel kaplama","Pilot ve uygulama testleri","Doğrulama ve sertifikasyon","Ölçek büyütme","Lisanslama / üretim","Küresel pazar"];

export const trTechnologies=[
  {slug:"dtpaper",name:"DTPaper®",label:"Tekstil dönüşümü",title:"DTF baskıda PET film yerine kâğıt.",summary:"Direct-to-Film tekstil baskı sürecinin tamamına göre geliştirilmiş, kâğıt bazlı, PET filmsiz ve silikonsuz transfer sistemi.",applications:["Talep üzerine tekstil baskısı","Promosyon tekstilleri","Kişiselleştirilmiş giysiler","Moda ve spor giyim","DTF baskı merkezleri","OEM ve sarf malzemesi ekosistemleri"],capabilities:["Mürekkep kabulü ve görüntü keskinliği","Sıcak eriyik toz tutunması","Fiksaj sıcaklığında boyutsal kararlılık","Görüntü transferi","Kontrollü ayırma","Renk, esneklik, tuşe ve yıkama performansı değerlendirmeleri"]},
  {slug:"ceralith",name:"Ceralith™",label:"Fırınlanabilir ambalaj dönüşümü",title:"PET film yerine mineral-reaktif bariyer.",summary:"PET film kullanılmadan fırınlanabilir kâğıt ve karton yapılar geliştirmek üzere tasarlanmış, su bazlı mineral-reaktif kaplama teknolojisi.",applications:["Fırınlanabilir karton tepsiler","Hazır yemek ambalajları","Pizza ve fırıncılık kartonları","Dondurulmuş fırın ürünleri","Gıda servis kartonları","Seçili pişirme kâğıdı yapıları","Seçili yüksek sıcaklık lif uygulamaları"],capabilities:["Isı dayanımı","Yağ ve gres dayanımı","Kaplama bütünlüğü","Yapıştırılabilirlik","Baskı ve dönüştürme uyumu","Nihai gıda temaslı yapı gereksinimleri"]},
  {slug:"bioma-orx",name:"Bioma-ORX®",label:"Gıda ambalajı dönüşümü",title:"Ayarlanabilir PFAS içermeyen lif bariyeri.",summary:"Kâğıt ve kartonda yağ, gres, nem ve seçilmiş sıvılara karşı direnç sağlamak üzere tasarlanmış, ayarlanabilir, su bazlı ve PFAS içermeyen bariyer platformu.",applications:["Burger, sandviç ve dürüm kâğıtları","Patates kızartması ve kızartılmış gıda ambalajları","Tereyağı ve yağlı süt ürünü kâğıtları","Pizza ve fırıncılık kutuları","Paket servis ambalajları","Gıda servis kartonları","Oluklu mukavva linerları","Gres dayanımlı kutu iç yüzeyleri","Seçili kâğıt ve karton yapıları"],capabilities:["Yağ ve gres bariyeri","Nem yönetimi","Ayarlanabilir bariyer performansı","Altlığa özel formülasyon","Baskı uyumu","Kesme, katlama ve yapıştırılabilirlik","Endüstriyel kaplama ölçeklenebilirliği"]},
] as const;

const trArticleSections = {
  "industrial-integration-problem":[
    ["Yönetici özeti","Plastikten kâğıda geçiş, tek bir malzemenin başkasıyla değiştirilmesi değildir. Kimya, lif altlık, kaplama, kurutma, dönüştürme, kalite kontrol ve nihai uygulamanın birlikte yeniden tasarlanmasıdır. Laboratuvarda umut veren bir numune üretim hızı, depolama, taşıma veya mevzuat incelemesiyle karşılaştığında başarısız olabilir. Güvenilir program, ölçek büyütmeden önce nihai yapıyı ve karar ölçütlerini tanımlar; laboratuvar, pilot ve endüstriyel kanıtı birbirinden ayırır."],
    ["Malzeme veya uygulama problemi","Bir plastik bileşen çoğu zaman ayırma, ısı dayanımı, bariyer, yapışma, boyutsal kararlılık veya baskı yüzeyi gibi birden fazla işlevi aynı anda sağlar. Kâğıda geçiş yalnızca görünür malzemeyi değil, bu işlevlerin tümünü etkiler. Lif yapı suyu emer, ısı ve neme tepki verir; lif bileşimi, gözeneklilik ve yüzey işlemiyle değişir. Esas soru, hangi lif yapı ve fonksiyonel işlemin üretim ile kullanım boyunca gerekli performansı sunabileceğidir."],
    ["Mevcut yapı neden kullanılıyor?","Mevcut yapılar genellikle tesadüf değildir. Kullanılabilir makineler, bilinen hammaddeler, öngörülebilir verim ve yerleşik test yöntemleri etrafında optimize edilmiştir. Operatörler proses pencerelerini, dönüştürücüler malzemenin katlanma veya yapışma davranışını, markalar da onaylı spesifikasyonları bilir. Tercih edilmeyen bir bileşen bile operasyon riskini azalttığı için sistemde kalabilir. Yeni rota mevcut katmanın işlevini, toleranslarını ve ekipmanın kabul edebileceği değişiklikleri anlamalıdır."],
    ["Değiştirme neden teknik olarak zor?","Bağımsız görünen işlevler birbirine bağlıdır. Kaplama miktarını artırmak bariyeri iyileştirirken kurutmayı yavaşlatabilir, bloklaşmayı artırabilir veya geri dönüşüm sonucunu değiştirebilir. Daha gözenekli kâğıt kaplama tutunmasını geliştirirken tüketimi artırabilir. Düz laboratuvar numunesinde başarılı formülasyon, katlama sonrasında çatlayabilir. Bu nedenle gerçek uygulama için asgari kabul edilebilir performans tanımlanmalı ve dönüştürülmüş nihai yapı test edilmelidir."],
    ["Endüstriyel entegrasyon gereksinimleri","Entegrasyon hedef hattan başlar: kaplama yöntemi, çalışma eni, web gerilimi, kurutma kapasitesi, uygulama miktarı, rulo yönetimi ve sonraki dönüştürme aşamaları kaydedilir. Program kritik kalite değişkenlerini ve gerçekçi proses penceresini belirlemeli, bunları hammadde kontrolleriyle bitmiş ürün testlerine bağlamalıdır. Pilot üretim; altlık, formülasyon sürümü, makine ayarları ve numune noktaları kayıtlıysa anlamlıdır. Teknoloji transferi hazırlama, güvenli kullanım ve değişiklik kontrolü talimatlarını da kapsar."],
    ["Validasyon kontrol listesi","Savunulabilir bir kayıt; uygulama, nihai malzeme yapısı, geliştirme aşaması, test veya demonstrasyon bağlamı, yöntem, sonuç özeti, tarih ve kanıt kaynağını belirtir. Sonuç hedef performans, doğrulama aşaması, pilot demonstrasyon, endüstriyel demonstrasyon, bağımsız doğrulama veya ticari mevcudiyet olarak açıkça etiketlenmelidir. Gıda teması, migrasyon, geri dönüştürülebilirlik ve mevzuat sonuçları hedef pazar için nihai yapıda değerlendirilmelidir. Sayısal iddialar onaylı kaynak ve test koşulu olmadan yayımlanmamalıdır."],
    ["PTP’nin geliştirme yaklaşımı","PTP malzeme problemiyle başlar ve mevcut yapının sağladığı her işlevi haritalar. Kimya ve altlık çalışması, hedef kaplama ve dönüştürme rotası göz önünde tutularak ilerler. Denemeler kontrollü kapılardan geçer: laboratuvar taraması, pilot uygulama, nihai kullanım testi, endüstriyel demonstrasyon ve uygun ticarileştirme yolu. Platform; malzeme geliştiricileri, üreticiler, dönüştürücüler, markalar ve doğrulama uzmanlarını aynı karar sürecinde buluşturur."],
    ["İlgili teknoloji","PTP platformu bu entegrasyon modelini DTPaper®, Ceralith™ ve Bioma-ORX® yollarında uygular. Her biri farklı bir uygulama probleminden başlasa da aynı disipline ihtiyaç duyar: sistemi tanımlamak, izlenebilirliği korumak ve iddiaları nihai kullanım konfigürasyonunda doğrulamak. Kurumlar mevcut bir malzeme, üretim kısıtı veya karşılanmamış performans hedefiyle başvurabilir. İlk proje adımı yapı, proses, maruziyet ve karar ölçütlerini teknik olarak anlamlı bir plan kuracak kadar net tanımlamaktır. Bu çerçeve, başarının hangi numunede ve hangi koşullarda gösterileceğini önceden açıklar. Böylece taraflar, yeni bir formülasyonun yalnızca umut verici olup olmadığını değil, mevcut üretim sistemine hangi kanıtlarla aktarılabileceğini de ortak bir dilde değerlendirebilir."],
  ],
  "hidden-plastic-carrier-dtf":[
    ["Yönetici özeti","Direct-to-Film tekstil baskısı görüntüyü kumaşa aktarır; ancak geçici taşıyıcı çoğunlukla tek kullanımlık PET filmdir. Bu taşıyıcıyı kâğıtla değiştirmek basit bir tabaka ikamesi değildir; ortam baskı, toz uygulama, kürleme, ısı presi ve ayırma aşamalarının tamamına katılır. Seçilen yazıcı, mürekkep, sıcak eriyik toz ve tekstille birlikte çalışması gerekir. DTPaper® bu nedenle her üretim yapılandırması için doğrulanan bütüncül bir transfer sistemi olarak geliştirilir."],
    ["Malzeme veya uygulama problemi","Taşıyıcı bitmiş giysiden transfer sonrasında ayrıldığı için, basılı tekstile odaklanan alıcılar tarafından kolayca gözden kaçabilir. Buna karşın her baskı, ıslak mürekkebi, toz birikimini, ısıya maruziyeti ve mekanik taşımayı yöneten kararlı bir geçici ortama ihtiyaç duyar. Lif seçimi, yüzey işlemi ve nem tepkisi bu sırayı etkiler. Değerlendirme, tek numunenin görsel olarak iyi olmasından ziyade iş akışının tutarlı çalışmasına odaklanmalıdır."],
    ["Mevcut yapı neden kullanılıyor?","PET film pürüzsüz, boyutsal olarak kararlı bir yüzey ve bilinen ayırma davranışı sunar. Yazıcılar, besleme sistemleri, tozlama makineleri, kürleme birimleri ve presler filmin kalınlığı, sertliği, sürtünmesi ve ısı tepkisine göre ayarlanmıştır. Operatörler de sıcak veya soğuk ayırma rutinlerini ve depolama uygulamalarını bilir. Kâğıt taşıyıcı mevcut alışkanlıklarla çalışmalı veya yönetilebilir bir geçiş rotası sunmalıdır."],
    ["Değiştirme neden teknik olarak zor?","Kâğıt hidrofiliktir ve doğal olarak değişkenlik gösterir. Fazla mürekkep emilimi renk yoğunluğunu ve çizgi netliğini azaltabilir; yetersiz tutunma ise toz katmanını bozabilir. Isı, nem hareketine, kıvrılmaya veya boyutsal değişime yol açarak kayıt ve beslemeyi etkileyebilir. Taşıyıcı kürleme sırasında yapıştırıcı sistemi tutarken, seçilen sıcaklık ve basınçta görüntüyü temiz biçimde bırakmalıdır. Bu özellikler birbirine bağlıdır ve ortak bir baskıdan yıkamaya protokolü gerektirir."],
    ["Endüstriyel entegrasyon gereksinimleri","Bir üretim incelemesi yazıcı modeli, mürekkep kimyası, çözünürlük, mürekkep yükü, toz tipi ve uygulaması, kürleme sıcaklık profili, bekleme süresi, taşıyıcı koşullandırması ve depolamayı kaydeder. Transfer doğrulaması tekstil bileşimi, pres sıcaklığı, basınç, süre ve ayırma yöntemini ekler. Besleme, statik davranış, rulo veya tabaka tutarlılığı, kenar kıvrılması ve operatör kullanımı da incelenmelidir. Bölgesel üretim veya lisanslama planlanıyorsa hammadde ve kalite kontrolleri teknoloji paketiyle aktarılmalıdır."],
    ["Validasyon kontrol listesi","Validasyon; görüntü netliği, renk tepkisi, toz tutunması, kürleme kararlılığı, transfer tamlığı, ayırma davranışı, tuşe, esneklik ve tanımlı protokolle yıkama performansını kapsamalıdır. Her sonuç belirli kâğıt, kaplama sürümü, yazıcı, mürekkep, toz, tekstil ve pres ayarlarıyla bağlantılı olmalıdır. PET filmsiz ve silikonsuz yapı iddiaları onaylı bileşim belgeleri gerektirir. Müşteriye özel sonuçlar, kaynak ve yayın izni açık olmadıkça gizli kalır."],
    ["PTP’nin geliştirme yaklaşımı","DTPaper® geliştirme süreci DTF akışını ve hedef kullanıcının kısıtlarını haritalamakla başlar. Kâğıt mühendisliği ve yüzey kimyası baskı ve transfer denemeleriyle birlikte ayarlanır. Sonuçlar görüntü kalitesi, operatör kullanımı ve giysi performansı dâhil tüm sistem için incelenir. Umut veren bir konfigürasyonda sonraki aşama tekrarlanabilirlik, çalışma uzunluğu ve parti kontrollerini genişletir. İş birliği doğrulanan yola göre doğrudan tedarik, dağıtım, OEM uyumu, bölgesel üretim veya lisanslama olabilir."],
    ["İlgili teknoloji","DTPaper®, DTF tekstil baskısı için kâğıt bazlı, PET filmsiz ve silikonsuz transfer sistemine odaklanan PTP yoludur. Sonuçlar seçilen yazıcı, mürekkep, sıcak eriyik toz, kürleme profili, tekstil, transfer sıcaklığı, basınç ve yıkama protokolüne bağlı olduğundan genel uyumluluk iddiasında bulunulmaz. Nitelikli bir proje bu iş akışını ve başarı ölçütlerini tanımlayarak başlar; ardından numuneleri, test koşullarını, kanıt sahipliğini ve endüstriyel benimseme adımlarını planlar. İlk teknik görüşmede mevcut film spesifikasyonu, günlük hacim, baskı modu, kürleme düzeni ve hedef tekstil ailesi paylaşılabilir. Bu bilgiler deneme matrisini daraltır, karşılaştırma numunesini belirler ve görsel kalitenin yanı sıra proses kararlılığı ile yıkama sonucunun aynı karar kapısında incelenmesini sağlar."],
  ],
  "pfas-free-industrial-packaging":[
    ["Yönetici özeti","PFAS temelli gres dayanımından PFAS içermeyen kâğıt ambalaja geçiş bir sistem geliştirme problemidir. Yeni kaplama; seçilen kâğıt veya kartonla, endüstriyel uygulama yöntemiyle, kurutma kapasitesiyle, baskı ve dönüştürme rotasıyla uyumlu olmalıdır. Ardından gerçek gıda, sıcaklık, temas süresi ve depolama koşullarında performans göstermelidir. Bioma-ORX® evrensel bir formülasyon değil, ayarlanabilir su bazlı ve PFAS içermeyen bariyer platformudur; tüm iddialar nihai ambalaj yapısında doğrulanır."],
    ["Malzeme veya uygulama problemi","Gıda servis kâğıt ve kartonları zorlu koşullarda yağ, gres, nem ve bazı sıvılarla karşılaşır. Burger kâğıdı, kızarmış gıda ambalajı, tereyağı kâğıdı ve oluklu mukavva linerı aynı maruziyet profiline sahip değildir. PFAS’ı çıkarmak kimya endişesini ele alır; ancak ambalajın ürünü tutması, görünümü koruması, güvenilir biçimde dönüştürülmesi ve ilgili gıda teması koşullarını karşılaması gerekir. Geliştirme bu nedenle gıda ve servis koşullarından başlar."],
    ["Mevcut yapı neden kullanılıyor?","Yerleşik gres dayanımlı yapılar düşük uygulama miktarlarında etkili performans sağlayabilir ve fabrika, kaplamacı ile dönüştürücü spesifikasyonlarına yerleşmiştir. Baskı, kesme, katlama, yapıştırma ve dolum davranışları bilinmektedir. Tedarik zincirlerinin onaylı test yöntemleri ve kalite eşikleri bulunur. PFAS içermeyen rota hem performansı hem de öngörülebilirliği karşılamalıdır. Birden fazla kâğıt kalitesi veya üretim sahasında çalışması gerekiyorsa proses toleransı ve parti tutarlılığı belirleyicidir."],
    ["Değiştirme neden teknik olarak zor?","Bariyer performansı formülasyonla lif yüzeyinin etkileşiminden doğar. Delikler, düzensiz yüzeyde kalma, kat yeri çatlakları, tutkal etkileşimi veya yaşlanma değişiklikleri başlangıçtaki düz tabaka sonucunu zayıflatabilir. Bariyeri artırmak hamurlaşma, baskı kabulü veya kurutma ihtiyacını etkileyebilir. Nem ve gres testleri yöntem, sıcaklık ve temas süresine göre farklı sonuç verir. Bitmiş ambalaj mürekkep, yapıştırıcı ve kesilmiş kenarlar da içerdiğinden kimya bilgisi tek başına uygunluk kanıtlamaz."],
    ["Endüstriyel entegrasyon gereksinimleri","Ölçek büyütme; desteklenen altlık kategorisini, kaplama yöntemini, uygulama miktarını, web hızını, kurutma profilini ve kalite kontrollerini tanımlar. Formülasyon hazırlama, filtrasyon, viskozite kontrolü, köpük yönetimi, kaplama homojenliği ve rulo depolama incelenmelidir. Sonraki denemeler baskı, kesme, piliyaj, katlama, yapıştırma ve paketleme koşullarını kapsar. Yararlı pilot çalışma altlığı, formülasyon partisini, makine parametrelerini, numune planını ve yaşlanma aralığını kaydeder; transferde izlenebilir değişiklik kontrolü gerekir."],
    ["Validasyon kontrol listesi","Plan; gıda türü veya simülanı, temas alanını, sıcaklığı, süreyi, depolama dönemini ve hedef pazarı tanımlar. Nihai kâğıt veya karton, kaplama miktarı, baskı ve dönüştürme yapılandırması kaydedilir. Bariyer yöntemleri ve kabul eşikleri testten önce kararlaştırılmalıdır. Gıda teması ve migrasyon değerlendirmesi nihai yapıyı ve kullanım koşullarını kapsamalıdır. PFAS içermeyen bileşim iddiası için tanımlı kapsam ve onaylı belge, kamuya açık sonuç için kaynak ve yayın izni gerekir."],
    ["PTP’nin geliştirme yaklaşımı","Bioma-ORX®, formülasyon seviyesi ile kaplama mimarisini altlık ve uygulama maruziyetine eşleştirerek geliştirilir. Laboratuvar taraması adayları daraltır; pilot kaplama çalışabilirliği ve homojenliği, dönüştürülmüş ambalaj denemeleri nihai kullanımı inceler. Kanıt, geniş bir ticari iddia yerine şeffaf olgunluk durumuyla sunulur. PTP kimya, kâğıt, kaplama, dönüştürme ve validasyon ekiplerini bir araya getirir. Ticari yol; kimyasal paket, uygulama geliştirme, endüstriyel doğrulama, bölgesel üretim veya lisanslama olabilir."],
    ["İlgili teknoloji","Bioma-ORX®, PTP’nin kâğıt ve kartonda yağ, gres, nem ve seçilmiş sıvılara karşı direnç için geliştirilen ayarlanabilir, su bazlı ve PFAS içermeyen bariyer platformudur. Seçili ambalaj kâğıtları, kızarmış gıda ambalajları, fırıncılık formatları, gıda servis kartonları ve linerlarda ele alınabilir. Uygunluk kategoriden çıkarılmaz. Proje altlık, kaplama miktarı, yağ ve nem maruziyeti, gıda türü, servis sıcaklığı, depolama, baskı ve dönüştürme koşullarını tanımlayarak başlar. Mevcut ambalaj ve gerçek ürün, başlangıç için en değerli karşılaştırma setini oluşturur. Teknik ekip buradan gerekli bariyer seviyesini, dönüştürme toleransını ve mevzuat inceleme kapsamını belirleyebilir; böylece gereğinden yüksek ve prosesi zorlaştıran tek tip bir hedef yerine uygulamaya uygun bir sistem geliştirilir."],
  ],
  "ovenable-paperboard-plastic-film":[
    ["Yönetici özeti","Fırınlanabilir karton; yapının aynı anda ısıya, yağa, dönüştürmeye ve gıda maruziyetine dayanması gerektiği için sıklıkla PET film kullanır. Filmi kaplamayla değiştirmek yalnızca sıcaklık dayanımı meselesi değildir. Nihai tepsi veya karton; oluşturma, baskı, yapıştırma, depolama, taşıma ve ısıtmada bütünlüğünü korumalıdır. Ceralith™ PET filmsiz fırınlanabilir kâğıt ve karton yapılarına yönelik su bazlı mineral-reaktif kaplama teknolojisidir; sonuçlar nihai yapıya özgüdür."],
    ["Malzeme veya uygulama problemi","Lif bazlı ambalaj, tüketici tarafından fark edilmeyen bir plastik film katmanı içerebilir. Fırınlanabilir yapılarda bu katman ısı tepkisi, gres dayanımı ve yüzey bütünlüğü sunarken lif geri kazanımını zorlaştırabilen kompozit bir yapı oluşturur. Filmi kaldırmak kartonun gıda, buhar, yağ ve fırın koşullarıyla etkileşimini değiştirir. Geliştirme görevi uygulamanın işlevlerini korurken endüstriyel olarak kaplanıp dönüştürülebilen bir yapı kurmaktır."],
    ["Mevcut yapı neden kullanılıyor?","PET lamine kartonun bilinen performans geçmişi ve yerleşik tedarik zinciri vardır. Dönüştürücüler baskı, kesme, piliyaj, şekillendirme ve yapıştırma sırasındaki davranışını bilir. Gıda üreticileri mevcut formatları kullanır; test programları tanımlı süre ve sıcaklık profillerine göre kurulmuştur. Film, zorlu maruziyete dayanabilen nispeten sürekli bir yüzey sunar. Kaplama temelli alternatif, tek bir laboratuvar ısıtma sonucundan fazlasını; hedef kullanım için benzer operasyonel kontrolü göstermelidir."],
    ["Değiştirme neden teknik olarak zor?","Isı yalnızca bir strestir. Yağlar kusurlardan geçebilir, buhar lif arayüzünü etkileyebilir, katlar kaplamayı çatlatabilir ve yapıştırıcılar dikişlerde farklı davranabilir. Altlık gözenekliliği ile kaplama miktarı yüzey örtmeyi; kurutma ve mineral reaksiyon koşulları bütünlüğü etkiler. Ambalaj ısıtmadan önce dondurma, soğuk depolama ve taşıma titreşimi yaşayabilir. Bu nedenle sıcaklık iddiaları süre, gıda veya simülan, altlık, kaplama miktarı ve ambalaj konfigürasyonu olmadan anlamlı değildir."],
    ["Endüstriyel entegrasyon gereksinimleri","Endüstriyel geliştirme; kâğıt veya karton spesifikasyonu, yüzey hazırlığı, kaplama yöntemi, kaplama miktarı aralığı, kurutma ve reaksiyon penceresi, rulo ya da tabaka kullanımı ve dönüştürme rotasını belirler. Pilot denemeler piliyaj veya şekillendirme öncesi ve sonrasında homojenlik, delik, bloklaşma, kıvrılma ve mekanik davranışı izlemelidir. Baskı ve yapıştırıcı uyumu ayrı kontrol edilir. Ölçek transferi formülasyon hazırlama, makine ayarları, kalite yöntemleri ve kabul limitlerinin belgelenmesini gerektirir."],
    ["Validasyon kontrol listesi","Test planı; ısıtma sıcaklığı ve süresini, gıda ürününü veya simülanı, dolum miktarını, ambalaj geometrisini, altlığı, kaplama miktarını, kurutma koşullarını ve dönüştürme yapısını kaydeder. Kaplama bütünlüğü, yağ ve gres dayanımı, sızıntı, boyutsal tepki, tutkal dikişleri ve uygulamaya özel güvenlik ölçütleri incelenir. Gıda teması ve migrasyon hedef pazar için nihai baskılı, dönüştürülmüş yapıda; geri dönüşüm sonucu uygun protokolle değerlendirilmelidir."],
    ["PTP’nin geliştirme yaklaşımı","Ceralith™ geliştirme süreci fırınlanabilir uygulamadan başlar ve mevcut laminatın sunduğu işlevleri haritalar. Mineral-reaktif kaplama tasarımı seçilen lif altlığa, uygulama yöntemine, kurutma koşullarına ve dönüştürücü gereksinimlerine bağlanır. Laboratuvar çalışması formülasyonları tarar; pilot çalışma yüzey örtme ve çalışabilirliği inceler; dönüştürülmüş yapılar hedef ısıtma bağlamında test edilir. Kanıt yalnızca onaylı koşul ve olgunluk durumuyla yayımlanır; ticari yol doğrulanan rotaya göre kurulur."],
    ["İlgili teknoloji","Ceralith™, seçilmiş fırınlanabilir kâğıt ve karton yapılarında PET filmsiz bir kaplama yoludur. Olası alanlar arasında seçili tepsiler, hazır yemek ambalajları, pizza ve fırıncılık kartonları, dondurulmuş fırın formatları, gıda servis kartonu ve diğer yüksek sıcaklık lif yapıları bulunur. Performans kâğıt veya kartona, kaplama miktarına, kurutma ve reaksiyon koşullarına, dönüştürme yapısına, gıda türüne, ısıtma sıcaklığına ve süresine bağlıdır. Teknik proje bu değişkenleri tanımlayarak başlar. Mevcut tepsi veya karton örneği, ısıtma talimatı, dolum profili ve dönüştürme çizimi ilk incelemenin kapsamını netleştirir. Ardından kaplama, mekanik şekillendirme, dikiş bütünlüğü ve ısı sonrası davranış aynı numune kimliğiyle izlenebilir; teknik ve ticari kararlar tek bir uygun test kaydına dayanabilir."],
  ],
} as const;

export const trApplicationNotes = {
  dtpaper:"DTPaper® performansı; kullanılan yazıcı, mürekkep, sıcak eriyik toz, fiksaj profili, tekstil türü, transfer sıcaklığı, basınç ve yıkama protokolüne bağlıdır. Uyumluluk ve nihai performans her üretim akışı için ayrıca doğrulanmalıdır.",
  ceralith:"Ceralith™ performansı; seçilen kâğıt veya karton, kaplama miktarı, kurutma ve reaksiyon koşulları, dönüştürme konfigürasyonu, gıda türü, ısıtma sıcaklığı ve süresine bağlıdır. Gıda teması, migrasyon, geri dönüştürülebilirlik ve nihai kullanım uygunluğu hedef pazar için son yapı üzerinde doğrulanmalıdır.",
  "bioma-orx":"Bioma-ORX® performansı; altlık, kaplama miktarı, yağ ve nem maruziyeti, gıda türü, servis sıcaklığı, depolama süresi, baskı ve dönüştürme koşullarına bağlıdır. Gıda teması, migrasyon, bariyer ve uygulamaya özel iddialar nihai ambalaj yapısı üzerinde doğrulanmalıdır.",
} as const;

export const trPages:Record<string,{eyebrow:string;title:string;intro:string;sections:Array<[string,string]>}>={
  platform:{eyebrow:"Platform",title:"Teknoloji, entegrasyonun kendisidir.",intro:"PTP, ölçeklenebilir lif bazlı teknolojiler geliştirmek ve küresel endüstriyel uygulamayı hızlandırmak için kurulmuş bağımsız uluslararası teknoloji ve iş birliği platformudur.",sections:[["Sorun","Malzeme inovasyonu parçalı ilerler; kimya, kâğıt, kaplama, dönüştürme ve validasyon sıklıkla ayrı ayrı optimize edilir."],["Platform yaklaşımı","PTP, tanımlı bir uygulama etrafında teknik disiplinleri bir araya getirir ve sistemi ölçek büyütme ile pazara erişim aşamalarına taşır."],["Pragmatik ilke","Lif bazlı teknolojilerin performans, üretim, mevzuat ve ekonomi koşullarını karşılayabildiği alanlarda PTP gerekli geçiş yolunu geliştirir."]]},
  technologies:{eyebrow:"Başlangıç portföyü",title:"Daha büyük bir platform için üç başlangıç noktası.",intro:"PTP’nin ilk teknolojileri tekstil baskısındaki gizli plastik taşıyıcıyı, fırınlanabilir kompozit yapıları ve problemli bariyer kimyasını ele alır.",sections:[]},
  "how-we-work":{eyebrow:"Nasıl çalışıyoruz",title:"Teknik potansiyelden endüstriyel sisteme.",intro:"PTP, malzeme geliştirme, endüstriyel entegrasyon, doğrulama ve ticarileştirmeyi tekrarlanabilir bir yol içinde birleştirir.",sections:[["Doğrulama ve demonstrasyon","Laboratuvar ve pilot denemeler, müşteri uygulama testleri ve performans doğrulaması."],["Optimizasyon ve ölçek büyütme","Kimya-altlık uyumu, makine, proses ve formülasyon optimizasyonu."],["Lisanslama ve teknoloji transferi","Uygulama paketleri, bölgesel üretim ve yapılandırılmış iş birlikleri."],["Kurulum ve devreye alma","Hat konfigürasyonu, proses kurulumu, eğitim ve üretim artışı."]]},
  "industrial-scale":{eyebrow:"Endüstriyel ölçek",title:"Bir kaplama teknolojisi ancak üretilebildiğinde değer kazanır.",intro:"PTP, laboratuvar kimyasından endüstriyel üretime geçişi desteklemek için formülasyon, altlık davranışı, makine koşulları, dönüştürme ve kalite kontrolü bir araya getirir.",sections:[["Endüstriyel entegrasyon","Kâğıt ve altlık seçimi, kaplama kimyası, ters gravür tecrübesi, kurutma ve kürleme optimizasyonu."],["Pilot ve doğrulama","Pilot üretim, test yöntemleri, kalite kontrol ve uygulamaya özel validasyon."],["Teknoloji transferi","Endüstriyel ölçek büyütme, üretim hazırlığı ve yapılandırılmış teknoloji transferi."]]},
  "for-brands":{eyebrow:"Markalar için",title:"Malzeme dönüşümünü ürün gerçeğine dönüştürün.",intro:"Somut bir malzeme değişikliği, mevzuata hazırlığı, ürün farklılaşmasını ve müşterilerin anlayabileceği bir dönüşüm hikâyesini destekleyebilir.",sections:[["Plastik bir bileşeni değiştirin","PET transfer taşıyıcısından kâğıt transfer ortamına geçiş."],["Problemli kimyayı çıkarın","PFAS yağ bariyerinden PFAS içermeyen lif bariyerine geçiş."],["Kompozit yapıyı sadeleştirin","PET lamine fırınlanabilir kartondan kaplanmış lif yapısına geçiş."]]},
  partners:{eyebrow:"Endüstri ve teknoloji ortakları",title:"Laboratuvarda çalışan bir teknolojiniz mi var?",intro:"PTP, kaplama entegrasyonu, doğrulama, ölçek büyütme, üretim ortaklığı veya küresel pazar erişimi gereken teknolojiler için endüstriyel geliştirme yolu sunar.",sections:[["Kâğıt fabrikaları","Fonksiyonel kâğıt geliştirme, lisanslama ve yeni ürün kategorileri."],["Dönüştürücüler ve kaplamacılar","Kaplama entegrasyonu, dönüştürme uyumu ve doğrulama."],["Kimya şirketleri","Umut vadeden kimyayı formülasyondan endüstriyel kaplamaya taşıma."],["Ekipman OEM’leri","Medya, makine ve proses uyumluluğu."],["Üniversiteler ve araştırma grupları","Laboratuvardan pilot ölçeğe geliştirme yolları."],["Girişimler ve malzeme bilimcileri","Ölçek büyütme, fikrî mülkiyet yolu ve pazar erişimi."],["Stratejik yatırımcılar","Ölçeklenebilir teknoloji portföyü ve uluslararası ticarileştirme."],["Üretim ortakları","Bölgesel üretim ve teknoloji transferi."]]},
  "global-hub":{eyebrow:"Küresel merkez",title:"Türkiye × Cambridge",intro:"Endüstriyel bilgi birikimi ile küresel ağlar tek bir teknoloji akışının tamamlayıcı parçalarıdır.",sections:[["Türkiye","Kimya, kaplama, pilot üretim, mühendislik ve üretim yolları."],["Cambridge ekosistemi","Bilimsel iş birliği, teknoloji taraması, lisanslama, yatırım ve uluslararasılaşma ağları."],["Açık konumlandırma","Cambridge ifadesi doğrulanmamış bir ofis veya tüzel kişilik iddiası değildir; bir ekosistem bağlantısını tanımlar."]]},
  "innovation-pipeline":{eyebrow:"Geliştirme hattı",title:"Portföy sürekli genişleyecek şekilde tasarlanmıştır.",intro:"Aşağıdaki alanlar mevcut ticari ürünler veya sertifikalı iddialar değil, hedeflenen inovasyon temalarıdır.",sections:[["Sentetik polimersiz ısıyla yapışma","Bardaklar, kapaklar, saşeler ve esnek kâğıt ambalajlar."],["Alüminyumsuz yüksek oksijen / nem bariyeri","Kahve, kuru gıdalar ve hassas ürünler."],["Isı yalıtımı ve koruyucu bariyer","Sıcak gıda, soğuk ve donuk gıda ile koruyucu lif ambalajları."]]},
  insights:{eyebrow:"İçgörüler",title:"Malzeme dönüşümü için teknik düşünce.",intro:"Lif bazlı teknoloji sistemlerinin ardındaki entegrasyon, uygulama ve endüstriyel ölçek sorularına yönelik analizler.",sections:[]},
  about:{eyebrow:"Hakkımızda",title:"İlk teknolojilerinden daha büyük bir platform.",intro:"PTP, malzeme problemlerini teknik kabiliyet ve küresel endüstriyel benimseme yollarıyla birleştirir.",sections:[["PTP","Ölçeklenebilir lif bazlı malzeme sistemlerine odaklanan bağımsız teknoloji ve iş birliği platformu."],["Canapa Paper Technologies","İlk teknolojilerin geliştiricisi; kaplama, uygulama ve endüstriyel ölçek büyütme kabiliyetini destekler."],["Cambridge ekosistemi","Bilim, iş birliği, lisanslama, yatırım ve uluslararasılaşma ağıyla bağlantı sağlar; fiziksel varlık iddiası değildir."]]},
  contact:{eyebrow:"Proje başvurusu",title:"Bir Dönüşüm Projesi Başlatın",intro:"Değiştirmek, geliştirmek veya endüstriyelleştirmek istediğiniz yapıyı anlatın. Teknik ayrıntı yararlıdır ancak zorunlu değildir.",sections:[]},
  privacy:{eyebrow:"Yasal",title:"Gizlilik Politikası",intro:"Proje formunda paylaştığınız bilgiler yalnızca talebinizi değerlendirmek ve yanıtlamak amacıyla işlenir.",sections:[["Veri minimizasyonu","Yalnızca proje değerlendirmesi için gerekli bilgiler talep edilir."],["Takip","Varsayılan olarak analiz veya reklam takibi etkin değildir."],["Güvenli belge paylaşımı","Teknik belgeler ilk değerlendirme sonrasında güvenli bir kanal üzerinden paylaşılır."]]},
  cookies:{eyebrow:"Yasal",title:"Çerez Politikası",intro:"Site varsayılan olarak isteğe bağlı analiz veya reklam çerezleri kullanmaz.",sections:[["Zorunlu teknolojiler","Barındırma, güvenlik ve oturum erişimi için gerekli teknikler kullanılabilir."],["Gelecekteki analizler","Herhangi bir analiz sağlayıcısı uygun onay mekanizması kurulmadan etkinleştirilmez."]]},
  "technical-disclaimer":{eyebrow:"Yasal",title:"Teknik Sorumluluk Reddi",intro:"Teknoloji açıklamaları garanti, sertifika, mevzuat onayı veya ticari uygunluk taahhüdü oluşturmaz.",sections:[["Uygulamaya özel doğrulama","Performans altlığa, kaplama miktarına, proses koşullarına, dönüştürme konfigürasyonuna ve nihai kullanıma bağlıdır."],["Geliştirme hedefleri","Geliştirme hattındaki alanlar ticari ürün olarak yorumlanmamalıdır."],["Nihai yapı","Gıda teması, mevzuat ve geri dönüştürülebilirlik iddiaları hedef pazar ve kullanım için nihai yapıda doğrulanmalıdır."]]},
};

const baseTrInsights=[
  {slug:"industrial-integration-problem",category:"Platform yaklaşımı",title:"Plastikten Kâğıda Dönüşüm Neden Bir Endüstriyel Entegrasyon Problemidir?",intro:"Umut vadeden bir formülasyon ancak kimya, altlık, kaplama, dönüştürme ve validasyon birlikte tasarlandığında uygulanabilir bir malzeme sistemine dönüşür.",technology:"PTP platformunu inceleyin",href:"/tr/platform",sections:[["Problem","Malzeme ikamesi çoğu zaman yeni bir kaplama veya altlık arayışı gibi ele alınır. Oysa belirleyici çalışma ilk başarılı laboratuvar sonucundan sonra başlar."],["Mevcut endüstriyel yapı","Kimya geliştiricileri, kâğıt üreticileri, kaplamacılar, dönüştürücüler, markalar ve mevzuat ekipleri aynı yapının farklı parçalarını ayrı ayrı optimize eder."],["Teknik zorluk","Lif yapı üretim hızında kaplanmalı, kurutulmalı, kürlenmeli, basılmalı, dönüştürülmeli ve performans göstermelidir."],["PTP yaklaşımı","PTP nihai uygulamadan başlar; kimya, altlık mühendisliği, kaplama koşulları, dönüştürme ve ticarileştirmeyi tek sistem olarak ele alır."],["Validasyon gereksinimi","Nihai yapı, test koşulları, proses ayarları ve hedef pazar kayıt altına alınmalı; laboratuvar, pilot ve endüstriyel sonuçlar ayrıştırılmalıdır."]]},
  {slug:"hidden-plastic-carrier-dtf",category:"Tekstil dönüşümü",title:"DTF Tekstil Baskısındaki Gizli Plastik Taşıyıcı",intro:"Hızla büyüyen bir baskı iş akışının merkezindeki PET taşıyıcı kolayca gözden kaçar; yerine başka bir yapı koymak ise teknik olarak zordur.",technology:"DTPaper®’ı inceleyin",href:"/tr/technologies/dtpaper",sections:[["Problem","DTF baskı görüntüyü tekstile aktarırken baskı, tozlama, kürleme ve transfer aşamalarında çoğunlukla tek kullanımlık PET film taşır."],["Mevcut endüstriyel yapı","Taşıyıcı; yazıcı, mürekkep, toz, fırın, pres ve operatör rutinleriyle bütünleşmiştir."],["Teknik zorluk","Kâğıt mürekkebi keskin biçimde kabul etmeli, sıcak eriyik tozu tutmalı, fiksaj sıcaklığında kararlı kalmalı, görüntüyü aktarmalı ve kontrollü ayrılmalıdır."],["PTP yaklaşımı","DTPaper®, kâğıt mühendisliği ve yüzey kimyasını renk, esneklik, tuşe ve yıkama performansıyla birlikte ele alan bir transfer sistemidir."],["Validasyon gereksinimi","Performans seçilen yazıcı, mürekkep, toz, kürleme profili, tekstil, pres koşulları ve yıkama protokolüyle doğrulanmalıdır."]]},
  {slug:"pfas-free-industrial-packaging",category:"Bariyer sistemleri",title:"PFAS İçermeyen Kimyadan Endüstriyel Gıda Ambalajına",intro:"Bir kimyayı çıkarmak başlangıçtır; yeni yapı kaplama, dönüştürme ve nihai uygulamanın gerçek koşullarını karşılamalıdır.",technology:"Bioma-ORX®’ı inceleyin",href:"/tr/technologies/bioma-orx",sections:[["Problem","Gıda temaslı kâğıt ve karton yağ, gres, nem veya seçili sıvılara karşı dayanım gerektirir; PFAS’ı çıkarmak bu işlevleri ortadan kaldırmaz."],["Mevcut endüstriyel yapı","Bariyer kimyası farklı altlıklara uygulanır; ardından baskı, kesme, katlama, yapıştırma, dolum ve kullanım aşamalarından geçer."],["Teknik zorluk","Kaplama bütünlüğü, dönüştürme uyumu ve endüstriyel çalışabilirlik korunurken performans ayarlanabilmelidir."],["PTP yaklaşımı","Bioma-ORX®, altlık, maruziyet, kaplama miktarı ve nihai kullanıma göre ayarlanan su bazlı, PFAS içermeyen bir bariyer platformudur."],["Validasyon gereksinimi","Nihai ambalaj gıda türü, sıcaklık, süre, hedef pazar ve dönüştürme yolu için test edilmelidir."]]},
  {slug:"ovenable-paperboard-plastic-film",category:"Fırınlanabilir ambalaj",title:"Fırınlanabilir Karton Neden Hâlâ Plastik Filme Bağımlı?",intro:"PET lamine fırınlanabilir yapıların kaplanmış lif sistemiyle değiştirilmesinde ısı dayanımı yalnızca bir gereksinimdir.",technology:"Ceralith™’i inceleyin",href:"/tr/technologies/ceralith",sections:[["Problem","Birçok fırınlanabilir karton yapı ısı ve yağ performansı için PET filme dayanır; bu kompozit yapı lif geri kazanımını zorlaştırabilir."],["Mevcut endüstriyel yapı","PET lamine karton; şekillendirme, dolum, taşıma, ısıtma ve gıda maruziyetine dayanması gereken formatlara dönüştürülür."],["Teknik zorluk","Kaplama temelli rota ısı dayanımı, yağ ve gres, kaplama bütünlüğü, yapıştırılabilirlik, baskı, dönüştürme ve gıda temaslı yapı gereksinimlerini birlikte yönetmelidir."],["PTP yaklaşımı","Ceralith™, PET filmsiz fırınlanabilir lif yapılarını araştırmak üzere tasarlanmış su bazlı mineral-reaktif kaplama teknolojisidir."],["Validasyon gereksinimi","Sayısal performans yayımlanmadan önce test sıcaklığı, süre, ürün veya simülan, altlık, kaplama miktarı ve dönüştürme konfigürasyonu kayıt altına alınmalıdır."]]},
] as const;

export const trInsights=baseTrInsights.map(article=>{const readingTimeMinutes=calculateReadingTime([article.intro,...trArticleSections[article.slug].flatMap(section=>[section[0],section[1]])],180);return ({
  ...article,
  published:"13 Ağustos 2026",
  updated:"13 Ağustos 2026",
  publishedIso:"2026-08-13",
  updatedIso:"2026-08-13",
  author:"PTP Teknik Editörya Ekibi",
  readingTimeMinutes,
  readingTime:`${readingTimeMinutes} dk okuma`,
  metaDescription:article.intro,
  sections:trArticleSections[article.slug],
});});
