import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import { ApplicationGallery, CeralithBreakthrough, ComparisonGallery, DTPaperImpactAward, DTPaperRealContext, EvidencePanel, GovernanceAccordion, HeritageSection, IndustrialDataPanel, IndustrialJourney, IndustrialPhotoStory, MaterialOutcomes, PlatformCTA, PlatformFragmentation, PlatformHero, PlatformPeople, PlatformPhases, PlatformStoryCollage, PlatformSystem, ProductStoryGallery, ProjectForm, RecognitionSection, TechnologyCards } from "../../components";
import { ceralithComparisonRecords, disclaimer, evidenceRecords, galleryRecords, globalHubMediaRecords, industrialParameters, insightArticles, platformMediaRecords, process as platformProcess, technologies, technologyDetails } from "../../../content/site";
import { corporateEmail } from "../../../content/contact";
import { leadershipProfiles } from "../../../content/leadership";

type Props = { params: Promise<{ slug: string[] }> };
const routes = ["platform","technologies","how-we-work","industrial-scale","for-brands","partners","global-hub","innovation-pipeline","insights","about","contact","privacy","cookies","technical-disclaimer"];

export async function generateStaticParams() { return [...routes.map(slug => ({slug:[slug]})), ...technologies.map(t => ({slug:["technologies",t.slug]})), ...insightArticles.map(a => ({slug:["insights",a.slug]}))]; }
export async function generateMetadata({params}: Props): Promise<Metadata> { const {slug} = await params; const key=slug.join("/"); const tech=technologies.find(t=>key===`technologies/${t.slug}`); const article=insightArticles.find(a=>key===`insights/${a.slug}`); const title=tech?.name || article?.title || titleMap[key] || "PTP"; const description=tech?.summary || article?.metaDescription || `Explore ${title} at the Plastic-to-Paper Technology Platform.`; return {title, description, alternates:{canonical:`/en/${key}`,languages:{"en-GB":`/en/${key}`,"tr-TR":`/tr/${key}`,"x-default":`/en/${key}`}},...(article?{openGraph:{type:"article",title,description,publishedTime:article.publishedIso,modifiedTime:article.updatedIso,authors:[article.author]},twitter:{card:"summary_large_image",title,description}}:{})}; }
const titleMap: Record<string,string> = {platform:"The Platform",technologies:"Technologies","how-we-work":"How We Work","industrial-scale":"Industrial Scale","for-brands":"For Brands",partners:"Industry & Technology Partners","global-hub":"Türkiye × Cambridge","innovation-pipeline":"Innovation Pipeline",insights:"Insights",about:"About PTP",contact:"Start a Transition Project",privacy:"Privacy Policy",cookies:"Cookie Policy","technical-disclaimer":"Technical Disclaimer"};

function PageHero({eyebrow,title,copy}:{eyebrow:string,title:string,copy:string}) { return <section className="page-hero"><p className="eyebrow light">{eyebrow}</p><h1>{title}</h1><p>{copy}</p><div className="page-hero-grid" aria-hidden="true"><i></i><i></i><i></i><i></i></div></section> }
function Disclaimer(){return <aside className="disclaimer"><b>Application note</b><p>{disclaimer}</p></aside>}
function SimpleCTA({title="Bring us the material challenge.",copy="We will connect the disciplines required to explore an industrial pathway.",accent}:{title?:string;copy?:string;accent?:string}){return <section className={`mini-cta contextual-cta ${accent||""}`}><h2>{title}</h2><p>{copy}</p><a className="button primary" href="/en/contact">Start a Project <span aria-hidden="true">→</span></a></section>}

function LeadershipSection(){const profiles=leadershipProfiles.filter(p=>p.publicationApproved);if(!profiles.length)return null;return <section className="section leadership"><div className="section-head"><p className="eyebrow">Leadership &amp; Technical Direction</p><h2>People accountable for platform direction and technical development.</h2></div><div className="leadership-grid">{profiles.map(p=><article key={p.fullName}><Image src={p.photograph} alt={p.photographAlt} width={640} height={760}/><span>{p.organisation}</span><h3>{p.fullName}</h3><b>{p.role}</b><p>{p.shortBiography}</p><p>{p.technicalExpertise.join(" · ")}</p><p>{p.relevantExperience}</p>{p.approvedProfileUrl&&<a className="partner-cta" href={p.approvedProfileUrl} rel="noreferrer">Professional profile ↗</a>}</article>)}</div></section>}

function Governance(){return <GovernanceAccordion/>}

function Platform(){return <><PlatformHero/><PlatformFragmentation/><PlatformSystem/><PlatformStoryCollage/><PlatformPeople/><HeritageSection/><Governance/><LeadershipSection/><PlatformPhases/><ApplicationGallery items={platformMediaRecords} eyebrow="Platform activity" heading="People, demonstrations and collaboration in context."/><MaterialOutcomes/><PlatformCTA/></>}

function Technologies(){return <><PageHero eyebrow="Initial portfolio" title="Three starting points for a larger platform." copy="PTP’s first technologies address hidden plastic carriers, ovenable composite structures and problematic barrier chemistry."/><section className="section technologies"><TechnologyCards/></section><section className="section business-model"><p className="eyebrow">Multiple paths from technology to market</p><div className="model-list">{["Direct product supply","Chemical package","Application development","Validation services","Technology licensing","Regional production","OEM collaboration","Strategic partnerships","Joint development"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></section><SimpleCTA/></>}

function Technology({slug}:{slug:string}) {
  const t=technologies.find(x=>x.slug===slug); if(!t) notFound();
  const evidence=technologyDetails[t.slug];
  const isD=t.slug==="dtpaper"; const isC=t.slug==="ceralith";
  const detail=isD?{hero:"Paper-Based DTF Transfer Media",heroCopy:"A paper-based, PET-film-free and silicone-free transfer system engineered for the complete Direct-to-Film textile printing workflow.",problem:"Designed around the complete DTF process—not simply as another sheet",challenge:"DTPaper® is engineered around ink acceptance, powder retention, fixation stability, image transfer and controlled release. Colour, flexibility, hand feel and wash performance remain part of the complete application review.",steps:["Print","Powder","Curing","Transfer"]}:isC?{hero:"Ovenable Fibre Packaging",heroCopy:"A water-based mineral-reactive coating technology designed to enable ovenable paper and board structures without PET film.",problem:"Heat, oil and converting must work together",challenge:"Ceralith™ targets ovenable fibre structures that balance temperature response, grease barrier, coating integrity, glueability, printing and conversion with the requirements of the final food-contact structure.",steps:["Substrate","Mineral coating","Dry / react","Convert & validate"]}:{hero:"PFAS-Free Fibre Barrier Systems",heroCopy:"An adjustable, water-based and PFAS-free barrier platform designed for oil, grease, moisture and selected liquid resistance on paper and board.",problem:"Different applications require different barrier profiles",challenge:"Bioma-ORX® is designed to tune oil, grease and moisture management around the substrate, coat weight, printing, converting route and final exposure—not force every application into one performance level.",steps:["Define exposure","Select substrate","Tune coating","Validate end use"]};
  const heroMedia=isD?{src:"/story/dtpaper-step-textile-v2.webp",alt:"Representative DTP textile transfer outcome"}:isC?{src:"/story/ceralith-ovenable-tray-v3.webp",alt:"Unbranded ovenable fibre tray application context"}:{src:"/story/bioma-pizza-box-application.webp",alt:"Pizza served in a corrugated fibre-based delivery box as representative food-packaging context"};
  return <>
    <section className={`page-hero product-hero product-${t.slug}`}><div className="product-hero-copy"><p className="eyebrow light">{t.label}</p><h1>{detail.hero}</h1><p>{detail.heroCopy}</p></div><div className="product-hero-media"><Image src={heroMedia.src} alt={heroMedia.alt} fill sizes="(max-width: 900px) calc(100vw - 44px), 55vw" quality={86} priority/><span>{t.name}</span><i></i><i></i><i></i></div></section>
    <section className="section tech-detail"><div><p className="eyebrow">The material challenge</p><h2>{detail.problem}</h2><p className="lead-dark">{detail.challenge}</p></div><div className={`material-sample ${t.accent}`}><span>{t.name}</span><i></i><i></i><i></i></div></section>
    {isC&&<section className="section why-it-matters"><p className="eyebrow">Why it matters</p><h2>Moving beyond a composite structure.</h2><p>PET lamination can provide important ovenable performance, but it also creates a multi-material structure that may complicate fibre recovery. Ceralith™ explores a coating-led route while keeping final performance, converting and food-contact validation at the centre of development.</p></section>}
    <section className="section tech-process"><p className="eyebrow">Application process</p><h2>Engineered around the workflow.</h2><div className="four-flow">{detail.steps.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div></section>
    {isD&&<><ProductStoryGallery technology={t.slug}/><DTPaperRealContext/><DTPaperImpactAward/></>}<ApplicationGallery items={galleryRecords[t.slug]} eyebrow={isD?"DTPaper® Application in Practice":isC?"Ceralith™ Application Exploration":"Bioma-ORX® Oil Barrier Demonstration"} heading={isD?"Print, process, cure and transfer—documented in one controlled sequence.":isC?"A real handling demonstration, published as application context rather than performance proof.":"Recorded OCC oil-barrier footage, kept distinct from representative application imagery."}/>{!isD&&<ProductStoryGallery technology={t.slug}/>} {isC&&<CeralithBreakthrough/>}
    <section className="section capability-grid-section"><div><p className="eyebrow">Technical capabilities</p><h2>A system of interdependent requirements.</h2></div><div className="capability-grid">{evidence.capabilities.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3></article>)}</div></section>
    <section className="section applications"><div><p className="eyebrow">Applications</p><h2>Designed for focused industrial use.</h2></div><div className="application-list">{evidence.applications.map(x=><span key={x}>{x}</span>)}</div></section>
    <EvidencePanel records={evidenceRecords[t.slug]}/>{isC&&<ComparisonGallery items={ceralithComparisonRecords}/>}<aside className="disclaimer"><b>Application note</b><p>{evidence.applicationNote}</p></aside>
    <section className="section business-model"><p className="eyebrow">Collaboration pathways</p><h2>Multiple paths from technology to market.</h2><div className="model-list">{evidence.collaboration.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></section><SimpleCTA title={isD?"Explore a paper-based DTF workflow.":isC?"Develop an ovenable fibre structure.":"Define the barrier profile your application needs."} accent={`cta-${t.slug}`}/>
  </>
}

function HowWeWork(){const modules=[["Validation & demonstration","Laboratory trials · pilot trials · application testing · performance validation"],["Optimisation & scale-up","Chemistry/substrate compatibility · process and formulation optimisation"],["Licensing & technology transfer","Application packages · regional production · royalty structures"],["Installation & commissioning","Line configuration · process setup · training · ramp-up"]];return <><PageHero eyebrow="How we work" title="From technical potential to industrial system." copy="PTP combines material development, industrial integration, validation and commercialisation in one repeatable pathway."/><section className="section module-grid">{modules.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h2>{a}</h2><p>{b}</p></article>)}</section><section className="section pathway"><div className="process">{platformProcess.map((p,i)=><div key={p}><span>{String(i+1).padStart(2,"0")}</span><p>{p}</p></div>)}</div></section><SimpleCTA/></>}

function Industrial(){return <><PageHero eyebrow="Industrial scale" title="A coating technology is only valuable when it can be manufactured." copy="PTP connects formulation, substrate behaviour, machine conditions, converting and quality control to support the transition from laboratory chemistry to industrial production."/><IndustrialPhotoStory/><section className="section capability-band"><div className="scale-visual"><div className="roll r1"></div><div className="roll r2"></div><div className="machine-line"></div></div><div><p className="eyebrow light">Scale-up capabilities</p><h2>Industrial integration, not a laboratory hand-off.</h2><p>Detailed operating capabilities and verified production parameters are shared within qualified technical discussions.</p></div></section><IndustrialJourney/><ApplicationGallery items={galleryRecords["industrial-scale"]} eyebrow="Industrial scale in practice" heading="Approved machine, coating and quality-control evidence."/><IndustrialDataPanel records={industrialParameters}/><SimpleCTA title="Move a coating technology toward industrial production." accent="cta-industrial"/></>}

function Brands(){return <><PageHero eyebrow="For brands" title="Turn material transition into product reality." copy="A precise material change can support regulatory preparation, product differentiation and a story customers can actually understand."/><section className="section project-types">{[["Replace a plastic component","PET transfer carrier → paper transfer medium"],["Remove problematic chemistry","PFAS grease barrier → PFAS-free fibre barrier"],["Simplify a composite structure","PET-laminated ovenable board → coated fibre structure"]].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h2>{a}</h2><p>{b}</p></article>)}</section><section className="section intake-preview"><div><p className="eyebrow">Bring us your current structure</p><h2>You do not need to arrive with a finished technical brief.</h2><p>Share what you know about the material, application, exposure conditions, production process and desired target. PTP can help define the problem.</p></div><a className="button primary" href="/en/contact">Describe Your Challenge</a></section></>}

function Partners(){const partners=[["Paper mills","Develop functional papers, licensing pathways and new product categories.","Explore functional paper development"],["Converters and coaters","Integrate coatings with converting conditions and structure-specific validation.","Start an integration project"],["Chemical companies","Take promising chemistry from formulation to industrial coating.","Submit a chemistry platform"],["Equipment OEMs","Align media, machine settings and process compatibility.","Explore OEM collaboration"],["Universities and research groups","Create a laboratory-to-pilot development pathway.","Discuss a research pathway"],["Startups and material scientists","Connect scale-up, IP strategy and market access.","Submit a technology"],["Strategic investors","Engage with a scalable technology portfolio and international commercialisation model.","Discuss strategic participation"],["Manufacturing partners","Evaluate regional production and structured technology transfer.","Explore regional manufacturing"]];return <><PageHero eyebrow="Industry & technology partners" title="Have a technology that works in the lab?" copy="PTP provides an industrial development pathway for technologies that need coating integration, validation, scale-up, manufacturing partnerships or global market access."/><section className="section stakeholder-grid partner-grid">{partners.map(([x,copy,cta],i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>{copy}</p><a className="partner-cta" href={`/en/contact?path=${encodeURIComponent(x)}`}>{cta} ↗</a></article>)}</section><RecognitionSection/><section className="final-cta"><h2>Multiple ways to build together.</h2><div className="actions"><a className="button primary" href="/en/contact">Submit a Technology</a><a className="button dark-outline" href="/en/contact">Explore Licensing</a></div></section></>}

function GlobalHub(){return <><PageHero eyebrow="Global hub" title="Türkiye × Cambridge" copy="Industrial knowledge and global networks are complementary parts of one technology flow—not separate stories."/><section className="section global"><div className="global-grid"><article><div className="location"><span>TR</span><h3>Türkiye</h3></div><p>Industrial capability</p><ul><li>Coating and chemistry</li><li>Pilot production</li><li>Engineering</li><li>Manufacturing</li></ul></article><div className="global-flow"><i></i><b>Science ↔ system ↔ scale</b><i></i></div><article><div className="location"><span>CB</span><h3>Cambridge</h3></div><p>Ecosystem connection</p><ul><li>Science collaboration</li><li>Technology scouting</li><li>Licensing and investment networks</li><li>Internationalisation</li></ul></article></div><p className="hub-note">“Cambridge” describes an ecosystem connection for science, collaboration, licensing, investment and internationalisation. It does not represent a stated office, company or physical facility.</p></section><ApplicationGallery items={globalHubMediaRecords} eyebrow="Hub activity" heading="Approved people, partner and event media."/><Governance/><SimpleCTA/></>}

function Pipeline(){return <><PageHero eyebrow="Development pipeline" title="The portfolio is designed to keep expanding." copy="The following areas are targeted innovation themes—not existing commercial products or certified claims."/><section className="section pipeline light-pipeline"><div className="pipeline-grid">{[["Synthetic-polymer-free heat seal","Cups · lids · sachets · flexible paper packaging"],["Aluminium-free high oxygen / moisture barrier","Coffee · dry foods · sensitive food products"],["Thermal insulation & protective barrier","Hot food · chilled and frozen food · protective fibre packaging"]].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section><Disclaimer/><SimpleCTA/></>}

function Insights(){return <><PageHero eyebrow="Insights" title="Technical thinking for material transition." copy="Analysis of the integration, application and industrial questions behind fibre-based technology systems."/><section className="section insight-grid">{insightArticles.map((a)=><article key={a.slug}><span>{a.category} · {a.readingTime}</span><h2>{a.title}</h2><p>{a.intro}</p><a className="arrow-link" href={`/en/insights/${a.slug}`}>Read insight ↗</a></article>)}</section></>}
function Article({slug}:{slug:string}){const a=insightArticles.find(x=>x.slug===slug);if(!a)notFound();const siteUrl=(process.env.NEXT_PUBLIC_SITE_URL||"https://ptp.technology").replace(/\/$/,"");const structuredData={"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.metaDescription,datePublished:a.publishedIso,dateModified:a.updatedIso,author:{"@type":"Organization",name:a.author},publisher:{"@type":"Organization",name:"Plastic-to-Paper Technology Platform"},inLanguage:"en-GB",mainEntityOfPage:`${siteUrl}/en/insights/${a.slug}`};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><PageHero eyebrow={a.category} title={a.title} copy={a.intro}/><article className="article-body"><dl className="article-meta"><div><dt>Published</dt><dd><time dateTime={a.publishedIso}>{a.published}</time></dd></div><div><dt>Updated</dt><dd><time dateTime={a.updatedIso}>{a.updated}</time></dd></div><div><dt>Author</dt><dd>{a.author}</dd></div><div><dt>Reading time</dt><dd>{a.readingTime}</dd></div></dl>{a.sections.map(([heading,copy])=><section key={heading}><h2>{heading}</h2><p>{copy}</p></section>)}<div className="article-cta"><p className="eyebrow">Related technology</p><h2>{a.technology}</h2><div className="actions"><a className="button primary" href={a.technologyHref}>Explore the technology</a><a className="button dark-outline" href="/en/contact">Start a Project</a></div></div><Disclaimer/></article></>}

function About(){return <><PageHero eyebrow="About" title="A platform larger than its first technologies." copy="PTP is structured to connect material challenges, technical capability and routes to global industrial adoption."/><section className="section editorial"><div className="editorial-cols"><article><p className="eyebrow">PTP</p><h2>The platform</h2><p>An independent international technology and collaboration platform focused on scalable fibre-based material systems.</p></article><article><p className="eyebrow">Industrial foundation</p><h2>Canapa capability</h2><p>The initial technologies were developed by Canapa Paper Technologies, which supports coating, application and industrial scale-up capability.</p></article></div></section><Governance/><LeadershipSection/><section className="section timeline"><div><span>NOW</span><h3>Initial portfolio</h3><p>DTPaper®, Ceralith™ and Bioma-ORX® establish the first technology pathways.</p></div><div><span>NEXT</span><h3>Expanding pipeline</h3><p>New barrier, sealing and protective material systems.</p></div><div><span>LONG TERM</span><h3>Global platform</h3><p>A continuously expanding network of technologies and industrial partners.</p></div></section><SimpleCTA/></>}

function Contact(){const addresses=[["General enquiries",corporateEmail.generalEnquiries],["Technology projects",corporateEmail.technologyProjects],["Licensing and partnerships",corporateEmail.licensingAndPartnerships]].filter((x):x is [string,string]=>Boolean(x[1]));const grouped=[...new Set(addresses.map(([,address])=>address))].map(address=>({address,label:addresses.filter(([,value])=>value===address).map(([label])=>label).join(" · ")}));return <><PageHero eyebrow="Project intake" title="Start a Transition Project" copy="Tell us what you want to replace, improve or industrialise. Technical detail is welcome but not required."/><section className="section contact-layout"><div><p className="eyebrow">The right starting point</p><h2>Bring the current structure—or simply the problem.</h2><p>PTP works with brands, mills, converters, printers, chemical developers, OEMs, researchers and strategic partners.</p><div className="contact-facts"><div><span>Target acknowledgement</span><b>Within two business days</b></div><div><span>Technical development &amp; industrialisation</span><b>Türkiye</b></div><div><span>Science, licensing &amp; internationalisation network</span><b>Cambridge ecosystem</b></div>{grouped.map(item=><div key={item.address}><span>{item.label}</span><a href={`mailto:${item.address}`}>{item.address}</a></div>)}</div><div className="contact-options"><span>Book a technical discussion</span><span>Explore licensing</span><span>Submit a technology</span></div></div><ProjectForm/></section><section className="section next-steps"><div className="section-head"><p className="eyebrow">What happens next?</p><h2>A clear path from enquiry to project.</h2></div><div className="four-flow">{[["Initial review","We assess the application, available information and best technical route."],["Technical discussion","The relevant material, process and commercial questions are clarified."],["Application and validation plan","Scope, structure, test context and decision criteria are defined."],["Commercial or partnership pathway","Supply, licensing, regional production or co-development routes are evaluated."]].map(([a,b],i)=><div key={a}><span>0{i+1}</span><b>{a}</b><p>{b}</p></div>)}</div></section></>}

function Legal({kind}:{kind:string}) { const content=kind==="privacy"?["We collect information you submit through the project form solely to evaluate and respond to your enquiry.","The production data controller identity, retention period, lawful basis, international transfer details and contact channel must be completed before public launch.","No analytics or marketing tracking is enabled by default."]:kind==="cookies"?["The site does not set optional analytics or advertising cookies by default.","Essential hosting and security technologies may be used to deliver the site. Any future analytics provider must be configured with an appropriate consent mechanism."]:[disclaimer,"Technology descriptions are informational and do not constitute warranties, certifications, regulatory approvals or a guarantee of commercial suitability.","Development pipeline items are targets and must not be interpreted as available commercial products."]; return <><PageHero eyebrow="Legal" title={titleMap[kind]} copy="Clear, technically precise information for users of the PTP website."/><section className="article-body legal-copy">{content.map((p,i)=><p key={i}>{p}</p>)}<p><b>Pre-launch note:</b> Legal entity details and an official contact address must be configured before public promotion.</p></section></> }

export default async function DynamicPage({params}:Props){const {slug}=await params;const key=slug.join("/");if(key==="platform")return <Platform/>;if(key==="technologies")return <Technologies/>;if(slug[0]==="technologies"&&slug[1])return <Technology slug={slug[1]}/>;if(key==="how-we-work")return <HowWeWork/>;if(key==="industrial-scale")return <Industrial/>;if(key==="for-brands")return <Brands/>;if(key==="partners")return <Partners/>;if(key==="global-hub")return <GlobalHub/>;if(key==="innovation-pipeline")return <Pipeline/>;if(key==="insights")return <Insights/>;if(slug[0]==="insights"&&slug[1])return <Article slug={slug[1]}/>;if(key==="about")return <About/>;if(key==="contact")return <Contact/>;if(["privacy","cookies","technical-disclaimer"].includes(key))return <Legal kind={key}/>;notFound()}
